import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// All 26 districts of AP with complete realistic Cold Storages
const COMPREHENSIVE_COLD_STORAGES = [
  // 1. Guntur
  {
    id: "cs-gnt-001",
    facilityName: "Sri Venkateswara Cold Storage & Agro Warehouse",
    registrationNumber: "AP-GNT-CS-2018-042",
    ownerId: "usr-owner-01",
    state: "Andhra Pradesh",
    district: "Guntur",
    mandal: "Guntur Urban",
    village: "Nallapadu",
    address: "Plot 14-18, Autonagar Industrial Area, Nallapadu, Guntur 522005",
    coordinates: { lat: 16.2890, lng: 80.4010 },
    totalCapacityMT: 8500,
    availableCapacityMT: 1200,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber A (Spices & Fresh Chilli)", tempRange: "4°C to 8°C", capacityMT: 4500, availableMT: 600, suitableCommodities: ["Fresh Chilli", "Turmeric"] },
      { name: "Chamber B (Fresh Fruits)", tempRange: "8°C to 12°C", capacityMT: 2500, availableMT: 450, suitableCommodities: ["Mango", "Sweet Orange", "Banana"] },
      { name: "Chamber C (Vegetables)", tempRange: "2°C to 5°C", capacityMT: 1500, availableMT: 150, suitableCommodities: ["Tomato", "Fresh Chilli"] }
    ],
    commoditiesSupported: ["Fresh Chilli", "Turmeric", "Mango", "Tomato", "Sweet Orange"],
    pricingPerMTMonth: 850,
    contactPerson: "K. Venkata Ramanayya",
    contactPhone: "+91 98480 55432",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "De-stoner", "Sorting & Grading Conveyor", "CCTV 24/7", "Power Backup (250 KVA)"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Owner Provided",
    sourceLastUpdated: "2026-09-27T10:00:00.000Z",
    lastVerified: "2026-09-27T14:30:00.000Z"
  },
  {
    id: "cs-gnt-002",
    facilityName: "Duggirala Turmeric Mega Cold Chain Terminal",
    registrationNumber: "AP-GNT-CS-2020-089",
    ownerId: "usr-owner-02",
    state: "Andhra Pradesh",
    district: "Guntur",
    mandal: "Duggirala",
    village: "Duggirala Village",
    address: "NH-16 By-pass Junction, Duggirala, Guntur 522330",
    coordinates: { lat: 16.3270, lng: 80.6275 },
    totalCapacityMT: 12000,
    availableCapacityMT: 3100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Controlled Atmosphere CA-1", tempRange: "2°C to 6°C", capacityMT: 7000, availableMT: 1900, suitableCommodities: ["Turmeric", "Fresh Chilli"] },
      { name: "Multi-Commodity Chamber B", tempRange: "10°C to 14°C", capacityMT: 5000, availableMT: 1200, suitableCommodities: ["Banana", "Mango"] }
    ],
    commoditiesSupported: ["Turmeric", "Fresh Chilli", "Banana", "Mango"],
    pricingPerMTMonth: 780,
    contactPerson: "M. Subba Rao",
    contactPhone: "+91 94405 88991",
    amenities: ["e-NAM Integrated Yard Access", "Humidity Controlled Dryers", "Weighbridge 100T", "Fumigation Chambers"],
    source: "APAMB Official Register",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-26T16:00:00.000Z"
  },
  {
    id: "cs-gnt-003",
    facilityName: "Tenali Spices & Agro Cold Preservation Hub",
    registrationNumber: "AP-GNT-CS-2021-104",
    ownerId: "usr-owner-01",
    state: "Andhra Pradesh",
    district: "Guntur",
    mandal: "Tenali",
    village: "Angalakuduru",
    address: "Tenali-Guntur Main Road, Angalakuduru, Tenali 522211",
    coordinates: { lat: 16.2430, lng: 80.6400 },
    totalCapacityMT: 6500,
    availableCapacityMT: 1400,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Chilli & Turmeric)", tempRange: "4°C to 8°C", capacityMT: 4000, availableMT: 800, suitableCommodities: ["Fresh Chilli", "Turmeric"] },
      { name: "Chamber 2 (Fresh Produce)", tempRange: "2°C to 6°C", capacityMT: 2500, availableMT: 600, suitableCommodities: ["Tomato", "Banana"] }
    ],
    commoditiesSupported: ["Fresh Chilli", "Turmeric", "Tomato", "Banana"],
    pricingPerMTMonth: 810,
    contactPerson: "K. Sambasiva Rao",
    contactPhone: "+91 98481 22334",
    amenities: ["Pre-cooling Unit", "Weighbridge 40T", "Power Backup", "CCTV 24/7"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T10:00:00.000Z",
    lastVerified: "2026-09-27T12:00:00.000Z"
  },

  // 2. Palnadu
  {
    id: "cs-pln-001",
    facilityName: "Palnadu Integrated Chilli & Spices Cold Store",
    registrationNumber: "AP-PLN-CS-2021-012",
    ownerId: "usr-owner-02",
    state: "Andhra Pradesh",
    district: "Palnadu",
    mandal: "Narasaraopet",
    village: "Ravipadu",
    address: "NH-544D Industrial Zone, Ravipadu, Narasaraopet 522601",
    coordinates: { lat: 16.2310, lng: 80.0520 },
    totalCapacityMT: 7500,
    availableCapacityMT: 1850,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber A (Dry & Fresh Chilli)", tempRange: "4°C to 8°C", capacityMT: 4500, availableMT: 1100, suitableCommodities: ["Fresh Chilli"] },
      { name: "Chamber B (Vegetables & Tomato)", tempRange: "2°C to 6°C", capacityMT: 3000, availableMT: 750, suitableCommodities: ["Tomato", "Lime"] }
    ],
    commoditiesSupported: ["Fresh Chilli", "Tomato", "Lime", "Papaya"],
    pricingPerMTMonth: 820,
    contactPerson: "Ch. Samba Siva Rao",
    contactPhone: "+91 94403 66789",
    amenities: ["Pre-cooling Unit", "Weighbridge 60T", "Sorting & Grading Conveyor", "Solar Hybrid Power Backup"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T08:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-pln-002",
    facilityName: "Chilakaluripet Agro & Lime Cold Terminal",
    registrationNumber: "AP-PLN-CS-2022-033",
    ownerId: "usr-owner-02",
    state: "Andhra Pradesh",
    district: "Palnadu",
    mandal: "Chilakaluripet",
    village: "Purushothapatnam",
    address: "NH-16 Bypass, Purushothapatnam, Chilakaluripet 522616",
    coordinates: { lat: 16.0890, lng: 80.1670 },
    totalCapacityMT: 6000,
    availableCapacityMT: 2200,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber L-1 (Citrus & Lime)", tempRange: "6°C to 10°C", capacityMT: 3500, availableMT: 1300, suitableCommodities: ["Lime", "Sweet Orange"] },
      { name: "Chamber L-2 (Chilli & Tomato)", tempRange: "3°C to 7°C", capacityMT: 2500, availableMT: 900, suitableCommodities: ["Fresh Chilli", "Tomato"] }
    ],
    commoditiesSupported: ["Lime", "Fresh Chilli", "Tomato", "Sweet Orange"],
    pricingPerMTMonth: 790,
    contactPerson: "Y. Srinivasa Reddy",
    contactPhone: "+91 98485 77123",
    amenities: ["Weighbridge 50T", "Pallet Storage", "Air Circulation Fans", "Genset 200 KVA"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T09:00:00.000Z",
    lastVerified: "2026-09-27T11:00:00.000Z"
  },

  // 3. Bapatla
  {
    id: "cs-bpt-001",
    facilityName: "Bapatla Coastal Agro & Banana Cold Logistics",
    registrationNumber: "AP-BPT-CS-2020-044",
    ownerId: "usr-owner-02",
    state: "Andhra Pradesh",
    district: "Bapatla",
    mandal: "Bapatla",
    village: "Appikatla",
    address: "Karlapalem Highway, Appikatla, Bapatla 522101",
    coordinates: { lat: 15.9010, lng: 80.4650 },
    totalCapacityMT: 5500,
    availableCapacityMT: 1600,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Banana Controlled Temp)", tempRange: "12°C to 14°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Banana", "Papaya"] },
      { name: "Chamber 2 (Cashew & Spices)", tempRange: "4°C to 8°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Cashew", "Fresh Chilli"] }
    ],
    commoditiesSupported: ["Banana", "Fresh Chilli", "Cashew", "Vegetables"],
    pricingPerMTMonth: 800,
    contactPerson: "P. Raghava Rao",
    contactPhone: "+91 94402 11988",
    amenities: ["Ripening Chambers", "Pre-cooling Dock", "Weighbridge 40T", "CCTV"],
    source: "AP Food Processing Society",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T14:00:00.000Z",
    lastVerified: "2026-09-26T16:00:00.000Z"
  },
  {
    id: "cs-bpt-002",
    facilityName: "Chirala Cashew & Marine-Agro Cold Chain",
    registrationNumber: "AP-BPT-CS-2021-081",
    ownerId: "usr-owner-02",
    state: "Andhra Pradesh",
    district: "Bapatla",
    mandal: "Chirala",
    village: "Vetapalem",
    address: "Vetapalem Industrial Road, Chirala 523157",
    coordinates: { lat: 15.8250, lng: 80.3520 },
    totalCapacityMT: 4500,
    availableCapacityMT: 800,
    operatingStatus: "Near Full",
    temperatureZones: [
      { name: "Chamber C-1 (Cashew & Dry Produce)", tempRange: "5°C to 10°C", capacityMT: 2500, availableMT: 300, suitableCommodities: ["Cashew"] },
      { name: "Chamber C-2 (Vegetables)", tempRange: "2°C to 5°C", capacityMT: 2000, availableMT: 500, suitableCommodities: ["Vegetables", "Tomato"] }
    ],
    commoditiesSupported: ["Cashew", "Vegetables", "Tomato", "Banana"],
    pricingPerMTMonth: 830,
    contactPerson: "D. Venkataramaiah",
    contactPhone: "+91 8594 223344",
    amenities: ["De-humidifier", "Weighbridge 50T", "24hr Power Backup"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T08:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },

  // 4. Krishna
  {
    id: "cs-kri-001",
    facilityName: "Nuzvid Royal Mango Cold Logistics",
    registrationNumber: "AP-KRI-CS-2021-033",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "Krishna",
    mandal: "Nuzvid",
    village: "Nuzvid Town",
    address: "Mylavaram Road, Nuzvid, Krishna 521201",
    coordinates: { lat: 16.7865, lng: 80.8465 },
    totalCapacityMT: 6000,
    availableCapacityMT: 2400,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber M-1 (Mango Specials)", tempRange: "10°C to 13°C", capacityMT: 4000, availableMT: 1800, suitableCommodities: ["Mango", "Guava"] },
      { name: "Chamber M-2 (Multi-Commodity)", tempRange: "4°C to 10°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Vegetables", "Banana"] }
    ],
    commoditiesSupported: ["Mango", "Guava", "Banana", "Tomato"],
    pricingPerMTMonth: 800,
    contactPerson: "N. Prasad Babu",
    contactPhone: "+91 94412 33445",
    amenities: ["Solar Powered Hybrid Backup", "Hot Water Immersion Treatment", "Grading Lines"],
    source: "National Horticulture Board (NHB)",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-20T10:00:00.000Z",
    lastVerified: "2026-09-24T15:30:00.000Z"
  },
  {
    id: "cs-kri-002",
    facilityName: "Gudivada Horticultural & Guava Cold Hub",
    registrationNumber: "AP-KRI-CS-2019-052",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "Krishna",
    mandal: "Gudivada",
    village: "Valivartipadu",
    address: "Gudivada Bypass, Valivartipadu, Krishna 521301",
    coordinates: { lat: 16.4410, lng: 80.9920 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1200,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Guava & Banana)", tempRange: "8°C to 12°C", capacityMT: 3000, availableMT: 700, suitableCommodities: ["Guava", "Banana"] },
      { name: "Chamber 2 (Mango & Vegetables)", tempRange: "4°C to 8°C", capacityMT: 2000, availableMT: 500, suitableCommodities: ["Mango", "Vegetables"] }
    ],
    commoditiesSupported: ["Guava", "Banana", "Mango", "Vegetables"],
    pricingPerMTMonth: 780,
    contactPerson: "V. Ramamohana Rao",
    contactPhone: "+91 98480 33211",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Automated Dataloggers"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T12:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  {
    id: "cs-kri-003",
    facilityName: "Machilipatnam Port Agro Cold Terminal",
    registrationNumber: "AP-KRI-CS-2022-091",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "Krishna",
    mandal: "Machilipatnam",
    village: "Chilakalapudi",
    address: "Port Road, Chilakalapudi, Machilipatnam 521002",
    coordinates: { lat: 16.1820, lng: 81.1350 },
    totalCapacityMT: 7000,
    availableCapacityMT: 2800,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Multi-Fruit Export)", tempRange: "4°C to 10°C", capacityMT: 4000, availableMT: 1600, suitableCommodities: ["Mango", "Banana"] },
      { name: "Chamber 2 (Vegetables)", tempRange: "2°C to 6°C", capacityMT: 3000, availableMT: 1200, suitableCommodities: ["Vegetables", "Tomato"] }
    ],
    commoditiesSupported: ["Mango", "Banana", "Vegetables", "Tomato"],
    pricingPerMTMonth: 820,
    contactPerson: "G. Satyanarayana",
    contactPhone: "+91 8672 255122",
    amenities: ["Reefer Van Dock", "Weighbridge 60T", "Blast Chiller"],
    source: "AP Food Processing Society",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T15:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },

  // 5. NTR
  {
    id: "cs-ntr-001",
    facilityName: "Nunna Mango & Horticultural Cold Storage Hub",
    registrationNumber: "AP-NTR-CS-2016-015",
    ownerId: "usr-owner-03",
    state: "Andhra Pradesh",
    district: "NTR",
    mandal: "Vijayawada Rural",
    village: "Nunna",
    address: "Near Nunna Mango Market Yard, Inner Ring Road, Vijayawada 521212",
    coordinates: { lat: 16.5823, lng: 80.6934 },
    totalCapacityMT: 10000,
    availableCapacityMT: 450,
    operatingStatus: "Near Full",
    temperatureZones: [
      { name: "Ripening & Cold Chamber 1", tempRange: "10°C to 13°C", capacityMT: 6000, availableMT: 200, suitableCommodities: ["Mango", "Papaya"] },
      { name: "Vegetable Preservation Unit", tempRange: "4°C to 8°C", capacityMT: 4000, availableMT: 250, suitableCommodities: ["Tomato", "Fresh Chilli"] }
    ],
    commoditiesSupported: ["Mango", "Papaya", "Tomato", "Fresh Chilli"],
    pricingPerMTMonth: 920,
    contactPerson: "G. Radha Krishna",
    contactPhone: "+91 866 2884433",
    amenities: ["Ethylene Ripening Chambers", "Reefer Van Fleet (5 units)", "Blast Chiller", "APEDA Export Packhouse"],
    source: "APEDA & AP Horticulture Dept",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T08:00:00.000Z",
    lastVerified: "2026-09-27T12:00:00.000Z"
  },
  {
    id: "cs-ntr-002",
    facilityName: "Jaggayyapeta Horticulture & Spices Depot",
    registrationNumber: "AP-NTR-CS-2021-067",
    ownerId: "usr-owner-03",
    state: "Andhra Pradesh",
    district: "NTR",
    mandal: "Jaggayyapeta",
    village: "Chillakallu",
    address: "NH-65 Hyderabad Highway, Chillakallu, Jaggayyapeta 521175",
    coordinates: { lat: 16.8920, lng: 80.0980 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1900,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Fresh Chilli & Spices)", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 1100, suitableCommodities: ["Fresh Chilli"] },
      { name: "Chamber 2 (Mango & Papaya)", tempRange: "8°C to 12°C", capacityMT: 2000, availableMT: 800, suitableCommodities: ["Mango", "Papaya"] }
    ],
    commoditiesSupported: ["Fresh Chilli", "Mango", "Papaya", "Tomato"],
    pricingPerMTMonth: 780,
    contactPerson: "M. Nageswara Rao",
    contactPhone: "+91 94406 55432",
    amenities: ["Weighbridge 50T", "Pre-cooling Chambers", "Power Backup"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T10:00:00.000Z",
    lastVerified: "2026-09-27T11:00:00.000Z"
  },

  // 6. Chittoor
  {
    id: "cs-ctr-001",
    facilityName: "Tirupati Agro Cold Chain & Export Packhouse",
    registrationNumber: "AP-CTR-CS-2021-008",
    ownerId: "usr-owner-09",
    state: "Andhra Pradesh",
    district: "Chittoor",
    mandal: "Palamaner",
    village: "Palamaner Town",
    address: "Bangalore - Chennai Corridor, Palamaner, Chittoor 517408",
    coordinates: { lat: 13.2015, lng: 78.7523 },
    totalCapacityMT: 9000,
    availableCapacityMT: 800,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Multi-fruit Chamber 1", tempRange: "8°C to 12°C", capacityMT: 5000, availableMT: 400, suitableCommodities: ["Mango", "Tomato"] },
      { name: "Pulp & Puree Freezer Cell", tempRange: "-18°C to -22°C", capacityMT: 4000, availableMT: 400, suitableCommodities: ["Mango Pulp", "Fruit Concentrate"] }
    ],
    commoditiesSupported: ["Mango", "Tomato", "Banana", "Papaya"],
    pricingPerMTMonth: 890,
    contactPerson: "V. Anand Kumar",
    contactPhone: "+91 8579 251122",
    amenities: ["Deep Freeze -20°C", "VHT (Vapour Heat Treatment) Line", "Export Documentation Support"],
    source: "APEDA Certified Cold Chain Directory",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T18:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-ctr-002",
    facilityName: "Chittoor Mango Pulp & Fruit Cold Terminal",
    registrationNumber: "AP-CTR-CS-2018-055",
    ownerId: "usr-owner-09",
    state: "Andhra Pradesh",
    district: "Chittoor",
    mandal: "Chittoor",
    village: "Murakambattu",
    address: "Industrial Estate, Murakambattu, Chittoor 517127",
    coordinates: { lat: 13.2180, lng: 79.1020 },
    totalCapacityMT: 8000,
    availableCapacityMT: 2100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber M-1 (Totapuri & Alphonso)", tempRange: "10°C to 13°C", capacityMT: 5000, availableMT: 1400, suitableCommodities: ["Mango"] },
      { name: "Chamber M-2 (Tomato & Banana)", tempRange: "4°C to 10°C", capacityMT: 3000, availableMT: 700, suitableCommodities: ["Tomato", "Banana"] }
    ],
    commoditiesSupported: ["Mango", "Tomato", "Banana", "Papaya"],
    pricingPerMTMonth: 860,
    contactPerson: "S. Mohan Reddy",
    contactPhone: "+91 8572 233890",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Automated Pulping Integration"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  {
    id: "cs-ctr-003",
    facilityName: "Kuppam Tri-Junction Agro Cold Depot",
    registrationNumber: "AP-CTR-CS-2022-098",
    ownerId: "usr-owner-09",
    state: "Andhra Pradesh",
    district: "Chittoor",
    mandal: "Kuppam",
    village: "Kuppam Town",
    address: "Bangalore Highway, Kuppam 517425",
    coordinates: { lat: 12.7520, lng: 78.3680 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1500,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Tomato & Vegetables)", tempRange: "3°C to 7°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Tomato"] },
      { name: "Chamber 2 (Mango & Papaya)", tempRange: "8°C to 12°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Mango", "Papaya"] }
    ],
    commoditiesSupported: ["Tomato", "Mango", "Papaya", "Banana"],
    pricingPerMTMonth: 820,
    contactPerson: "K. Murali Krishna",
    contactPhone: "+91 94404 88712",
    amenities: ["Weighbridge 40T", "Solar Rooftop (150 KW)", "Transit Dock"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T14:00:00.000Z",
    lastVerified: "2026-09-27T09:30:00.000Z"
  },

  // 7. Tirupati
  {
    id: "cs-tpt-001",
    facilityName: "Srikalahasti Agro & Citrus Cold Logistics",
    registrationNumber: "AP-TPT-CS-2020-031",
    ownerId: "usr-owner-05",
    state: "Andhra Pradesh",
    district: "Tirupati",
    mandal: "Srikalahasti",
    village: "Yerpedu",
    address: "Renigunta - Srikalahasti Highway, Yerpedu, Tirupati 517619",
    coordinates: { lat: 13.7490, lng: 79.7020 },
    totalCapacityMT: 6500,
    availableCapacityMT: 1800,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber C-1 (Acid Lime & Citrus)", tempRange: "6°C to 10°C", capacityMT: 4000, availableMT: 1100, suitableCommodities: ["Lime", "Sweet Orange"] },
      { name: "Chamber C-2 (Mango & Tomato)", tempRange: "4°C to 8°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Mango", "Tomato"] }
    ],
    commoditiesSupported: ["Lime", "Mango", "Tomato", "Cashew"],
    pricingPerMTMonth: 810,
    contactPerson: "P. Venkata Subbaiah",
    contactPhone: "+91 877 2289110",
    amenities: ["Waxing Table", "Weighbridge 50T", "Pre-cooling Cells", "Genset Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T16:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-tpt-002",
    facilityName: "Renigunta Airport Agro Cargo Cold Terminal",
    registrationNumber: "AP-TPT-CS-2022-076",
    ownerId: "usr-owner-05",
    state: "Andhra Pradesh",
    district: "Tirupati",
    mandal: "Tirupati Urban",
    village: "Renigunta",
    address: "Airport Road, Settipalli, Renigunta, Tirupati 517520",
    coordinates: { lat: 13.6520, lng: 79.5180 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1300,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Air Cargo Packhouse (Chilled)", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 800, suitableCommodities: ["Mango", "Tomato"] },
      { name: "Tropical Fruit Zone", tempRange: "10°C to 14°C", capacityMT: 2000, availableMT: 500, suitableCommodities: ["Papaya", "Banana"] }
    ],
    commoditiesSupported: ["Mango", "Tomato", "Papaya", "Lime"],
    pricingPerMTMonth: 880,
    contactPerson: "R. Jayachandra",
    contactPhone: "+91 94411 77654",
    amenities: ["Reefer Docking Bays", "APEDA Inspection Area", "X-Ray Scanner Integration"],
    source: "APEDA & AP State Warehouse Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T08:00:00.000Z",
    lastVerified: "2026-09-27T11:00:00.000Z"
  },
  {
    id: "cs-tpt-003",
    facilityName: "Gudur Coastal Citrus & Cashew Cold Facility",
    registrationNumber: "AP-TPT-CS-2019-019",
    ownerId: "usr-owner-05",
    state: "Andhra Pradesh",
    district: "Tirupati",
    mandal: "Gudur",
    village: "Chillakur",
    address: "Chennai - Kolkata NH-16, Chillakur, Gudur 524101",
    coordinates: { lat: 14.1480, lng: 79.8510 },
    totalCapacityMT: 4500,
    availableCapacityMT: 1100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Lime & Citrus Chamber", tempRange: "7°C to 10°C", capacityMT: 2500, availableMT: 600, suitableCommodities: ["Lime"] },
      { name: "Cashew & Dry Goods Chamber", tempRange: "5°C to 9°C", capacityMT: 2000, availableMT: 500, suitableCommodities: ["Cashew"] }
    ],
    commoditiesSupported: ["Lime", "Cashew", "Mango", "Vegetables"],
    pricingPerMTMonth: 790,
    contactPerson: "T. Sudhakar Rao",
    contactPhone: "+91 8624 251188",
    amenities: ["De-stoner", "Weighbridge 40T", "Automated Humidifiers"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T07:30:00.000Z"
  },

  // 8. Annamayya
  {
    id: "cs-amm-001",
    facilityName: "Madanapalle High-Altitude Tomato & Multi-Crop Cold Storage",
    registrationNumber: "AP-AMM-CS-2019-077",
    ownerId: "usr-owner-05",
    state: "Andhra Pradesh",
    district: "Annamayya",
    mandal: "Madanapalle",
    village: "Basinikonda",
    address: "Basinikonda Industrial Estate, Madanapalle 517325",
    coordinates: { lat: 13.5510, lng: 78.5020 },
    totalCapacityMT: 5000,
    availableCapacityMT: 350,
    operatingStatus: "Near Full",
    temperatureZones: [
      { name: "Chamber T-1 (Tomato Controlled Humidity)", tempRange: "10°C to 13°C", capacityMT: 3500, availableMT: 200, suitableCommodities: ["Tomato"] },
      { name: "Chamber T-2 (Fruit & Papaya)", tempRange: "10°C to 14°C", capacityMT: 1500, availableMT: 150, suitableCommodities: ["Papaya", "Mango"] }
    ],
    commoditiesSupported: ["Tomato", "Papaya", "Mango"],
    pricingPerMTMonth: 950,
    contactPerson: "C. Surendra Naidu",
    contactPhone: "+91 8571 228899",
    amenities: ["Hydro-cooling wash tanks", "Crate sterilization", "Weighbridge 40T", "Refrigerated Transit Dock"],
    source: "AP Cold Chain Portal",
    sourceType: "Owner Provided",
    sourceLastUpdated: "2026-09-27T07:30:00.000Z",
    lastVerified: "2026-09-27T11:00:00.000Z"
  },
  {
    id: "cs-amm-002",
    facilityName: "Rayachoti Papaya & Sweet Orange Cold Hub",
    registrationNumber: "AP-AMM-CS-2022-045",
    ownerId: "usr-owner-05",
    state: "Andhra Pradesh",
    district: "Annamayya",
    mandal: "Rayachoti",
    village: "Sambepalli",
    address: "Kadapa - Bengaluru Road, Sambepalli, Rayachoti 516269",
    coordinates: { lat: 14.0580, lng: 78.7560 },
    totalCapacityMT: 6000,
    availableCapacityMT: 2100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Papaya & Banana)", tempRange: "12°C to 14°C", capacityMT: 3500, availableMT: 1200, suitableCommodities: ["Papaya", "Banana"] },
      { name: "Chamber 2 (Tomato & Sweet Orange)", tempRange: "5°C to 10°C", capacityMT: 2500, availableMT: 900, suitableCommodities: ["Tomato", "Sweet Orange"] }
    ],
    commoditiesSupported: ["Papaya", "Banana", "Tomato", "Sweet Orange"],
    pricingPerMTMonth: 820,
    contactPerson: "M. Bhaskara Reddy",
    contactPhone: "+91 94405 66123",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Solar Power Backup"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T14:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },

  // 9. Ananthapuramu
  {
    id: "cs-atp-001",
    facilityName: "Rayalaseema Citrus & Sweet Orange Cold Chain",
    registrationNumber: "AP-ATP-CS-2022-019",
    ownerId: "usr-owner-07",
    state: "Andhra Pradesh",
    district: "Ananthapuramu",
    mandal: "Tadipatri",
    village: "Tadipatri Rural",
    address: "Tadipatri - Kadapa Bypass Road, Ananthapuramu 515411",
    coordinates: { lat: 14.9080, lng: 78.0120 },
    totalCapacityMT: 6500,
    availableCapacityMT: 2100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Citrus Precision Cell A", tempRange: "5°C to 8°C", capacityMT: 4500, availableMT: 1400, suitableCommodities: ["Sweet Orange", "Pomegranate"] },
      { name: "Banana Ripening / Holding Cell B", tempRange: "12°C to 15°C", capacityMT: 2000, availableMT: 700, suitableCommodities: ["Banana", "Papaya"] }
    ],
    commoditiesSupported: ["Sweet Orange", "Banana", "Pomegranate", "Papaya"],
    pricingPerMTMonth: 820,
    contactPerson: "D. Sreenivasulu",
    contactPhone: "+91 94402 77112",
    amenities: ["Degreening Room", "Automatic Sizing Roller Table", "Waxing Line", "Weighbridge 60T"],
    source: "National Centre for Cold-chain Development (NCCD)",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-22T09:00:00.000Z",
    lastVerified: "2026-09-25T11:00:00.000Z"
  },
  {
    id: "cs-atp-002",
    facilityName: "Ananthapuramu Precision Pomegranate & Horticulture Store",
    registrationNumber: "AP-ATP-CS-2020-058",
    ownerId: "usr-owner-07",
    state: "Andhra Pradesh",
    district: "Ananthapuramu",
    mandal: "Ananthapuramu",
    village: "Atmakur",
    address: "Bellary Road, Atmakur, Ananthapuramu 515751",
    coordinates: { lat: 14.6850, lng: 77.6050 },
    totalCapacityMT: 7000,
    availableCapacityMT: 2600,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber P-1 (Pomegranate & Sweet Orange)", tempRange: "5°C to 8°C", capacityMT: 4000, availableMT: 1500, suitableCommodities: ["Pomegranate", "Sweet Orange"] },
      { name: "Chamber P-2 (Papaya & Vegetables)", tempRange: "8°C to 12°C", capacityMT: 3000, availableMT: 1100, suitableCommodities: ["Papaya", "Tomato"] }
    ],
    commoditiesSupported: ["Pomegranate", "Sweet Orange", "Papaya", "Tomato"],
    pricingPerMTMonth: 840,
    contactPerson: "K. Ramanjaneyulu",
    contactPhone: "+91 8554 277334",
    amenities: ["Weighbridge 50T", "Pre-cooling Chambers", "Humidity Controlled Docks"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T15:00:00.000Z",
    lastVerified: "2026-09-27T08:30:00.000Z"
  },
  {
    id: "cs-atp-003",
    facilityName: "Guntakal Junction Multi-Commodity Cold Depot",
    registrationNumber: "AP-ATP-CS-2021-088",
    ownerId: "usr-owner-07",
    state: "Andhra Pradesh",
    district: "Ananthapuramu",
    mandal: "Guntakal",
    village: "Kasapuram",
    address: "Railway Bypass Road, Kasapuram, Guntakal 515803",
    coordinates: { lat: 15.1720, lng: 77.3780 },
    totalCapacityMT: 5500,
    availableCapacityMT: 1900,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Railway Transit Chamber", tempRange: "4°C to 8°C", capacityMT: 3500, availableMT: 1200, suitableCommodities: ["Sweet Orange", "Pomegranate"] },
      { name: "Banana Ripening Chamber", tempRange: "12°C to 15°C", capacityMT: 2000, availableMT: 700, suitableCommodities: ["Banana"] }
    ],
    commoditiesSupported: ["Sweet Orange", "Pomegranate", "Banana", "Tomato"],
    pricingPerMTMonth: 790,
    contactPerson: "V. Somasekhar",
    contactPhone: "+91 94408 99123",
    amenities: ["Direct Rail Freight Access", "Weighbridge 60T", "Power Backup"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T14:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },

  // 10. Sri Sathya Sai
  {
    id: "cs-sss-001",
    facilityName: "Hindupur Industrial Border Cold Logistics",
    registrationNumber: "AP-SSS-CS-2021-022",
    ownerId: "usr-owner-07",
    state: "Andhra Pradesh",
    district: "Sri Sathya Sai",
    mandal: "Hindupur",
    village: "Lepakshi",
    address: "Bengaluru Highway NH-44, Lepakshi, Hindupur 515331",
    coordinates: { lat: 13.8290, lng: 77.4920 },
    totalCapacityMT: 6000,
    availableCapacityMT: 1700,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber H-1 (Citrus & Sweet Orange)", tempRange: "5°C to 8°C", capacityMT: 3500, availableMT: 1000, suitableCommodities: ["Sweet Orange", "Pomegranate"] },
      { name: "Chamber H-2 (Mango & Banana)", tempRange: "10°C to 14°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Mango", "Banana"] }
    ],
    commoditiesSupported: ["Sweet Orange", "Pomegranate", "Mango", "Banana"],
    pricingPerMTMonth: 850,
    contactPerson: "B. Gangadhar Reddy",
    contactPhone: "+91 8556 221190",
    amenities: ["Reefer Docking", "Pre-cooling", "Weighbridge 50T", "Power Backup (200 KVA)"],
    source: "AP Food Processing Society",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T12:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-sss-002",
    facilityName: "Dharmavaram Sweet Orange & Horticultural Store",
    registrationNumber: "AP-SSS-CS-2020-049",
    ownerId: "usr-owner-07",
    state: "Andhra Pradesh",
    district: "Sri Sathya Sai",
    mandal: "Dharmavaram",
    village: "Bathalapalli",
    address: "Bathalapalli Road, Dharmavaram 515671",
    coordinates: { lat: 14.4150, lng: 77.7210 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1400,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Citrus Cell", tempRange: "5°C to 9°C", capacityMT: 3000, availableMT: 800, suitableCommodities: ["Sweet Orange"] },
      { name: "Vegetable Cell", tempRange: "2°C to 6°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Tomato", "Banana"] }
    ],
    commoditiesSupported: ["Sweet Orange", "Banana", "Tomato", "Mango"],
    pricingPerMTMonth: 810,
    contactPerson: "P. Chandra Mohan",
    contactPhone: "+91 98488 44556",
    amenities: ["Waxing Table", "Weighbridge 40T", "Automated Dataloggers"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T10:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 11. Kurnool
  {
    id: "cs-knl-001",
    facilityName: "Tungabhadra Fresh Chilli & Spices Preservation Cold Store",
    registrationNumber: "AP-KNL-CS-2017-062",
    ownerId: "usr-owner-06",
    state: "Andhra Pradesh",
    district: "Kurnool",
    mandal: "Kurnool Urban",
    village: "Gargeyapuram",
    address: "NH-44 Bengaluru Highway, Gargeyapuram, Kurnool 518002",
    coordinates: { lat: 15.8010, lng: 78.0750 },
    totalCapacityMT: 8000,
    availableCapacityMT: 2800,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Precision Temperature Chamber 1", tempRange: "7°C to 10°C", capacityMT: 5000, availableMT: 1600, suitableCommodities: ["Fresh Chilli", "Sweet Orange"] },
      { name: "Fresh Chilli & Vegetable Chamber 2", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 1200, suitableCommodities: ["Fresh Chilli", "Tomato"] }
    ],
    commoditiesSupported: ["Fresh Chilli", "Tomato", "Sweet Orange"],
    pricingPerMTMonth: 720,
    contactPerson: "B. Prabhakar Reddy",
    contactPhone: "+91 8518 255677",
    amenities: ["Forced Air Drying Ventilation", "Direct Highway Ramp Access", "24hr Genset Backup"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-24T14:00:00.000Z",
    lastVerified: "2026-09-26T10:00:00.000Z"
  },
  {
    id: "cs-knl-002",
    facilityName: "Adoni Commercial Agro & Spices Cold Terminal",
    registrationNumber: "AP-KNL-CS-2021-039",
    ownerId: "usr-owner-06",
    state: "Andhra Pradesh",
    district: "Kurnool",
    mandal: "Adoni",
    village: "Mandagiri",
    address: "Adoni - Alur Road, Mandagiri, Adoni 518301",
    coordinates: { lat: 15.6320, lng: 77.2750 },
    totalCapacityMT: 6500,
    availableCapacityMT: 2300,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber A-1 (Fresh Chilli & Spices)", tempRange: "4°C to 8°C", capacityMT: 4000, availableMT: 1400, suitableCommodities: ["Fresh Chilli"] },
      { name: "Chamber A-2 (Tomato & Vegetables)", tempRange: "2°C to 6°C", capacityMT: 2500, availableMT: 900, suitableCommodities: ["Tomato", "Sweet Orange"] }
    ],
    commoditiesSupported: ["Fresh Chilli", "Tomato", "Sweet Orange", "Banana"],
    pricingPerMTMonth: 740,
    contactPerson: "V. Mallikarjuna",
    contactPhone: "+91 8512 253321",
    amenities: ["Weighbridge 60T", "Pre-cooling Fans", "Solar Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 12. Nandyal
  {
    id: "cs-ndl-001",
    facilityName: "Nandyal Golden Agri & Turmeric Cold Chain",
    registrationNumber: "AP-NDL-CS-2020-018",
    ownerId: "usr-owner-06",
    state: "Andhra Pradesh",
    district: "Nandyal",
    mandal: "Nandyal",
    village: "Chabolu",
    address: "Gooty - Kurnool Highway, Chabolu, Nandyal 518501",
    coordinates: { lat: 15.4820, lng: 78.4890 },
    totalCapacityMT: 7500,
    availableCapacityMT: 2500,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber N-1 (Turmeric & Spices)", tempRange: "4°C to 8°C", capacityMT: 4500, availableMT: 1500, suitableCommodities: ["Turmeric", "Fresh Chilli"] },
      { name: "Chamber N-2 (Banana & Sweet Orange)", tempRange: "8°C to 12°C", capacityMT: 3000, availableMT: 1000, suitableCommodities: ["Banana", "Sweet Orange"] }
    ],
    commoditiesSupported: ["Turmeric", "Fresh Chilli", "Banana", "Sweet Orange"],
    pricingPerMTMonth: 760,
    contactPerson: "K. Raghunatha Reddy",
    contactPhone: "+91 8514 244199",
    amenities: ["Weighbridge 50T", "De-humidifier", "Pre-cooling Units", "Power Backup"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T14:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-ndl-002",
    facilityName: "Allagadda Turmeric & Horticultural Cold Hub",
    registrationNumber: "AP-NDL-CS-2022-064",
    ownerId: "usr-owner-06",
    state: "Andhra Pradesh",
    district: "Nandyal",
    mandal: "Allagadda",
    village: "Rudravaram",
    address: "NH-40 Bypass, Rudravaram, Allagadda 518543",
    coordinates: { lat: 15.1320, lng: 78.5120 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1600,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Turmeric Precision Chamber", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Turmeric"] },
      { name: "Banana Ripening Chamber", tempRange: "12°C to 15°C", capacityMT: 2000, availableMT: 700, suitableCommodities: ["Banana"] }
    ],
    commoditiesSupported: ["Turmeric", "Banana", "Sweet Orange", "Fresh Chilli"],
    pricingPerMTMonth: 780,
    contactPerson: "Y. Narayana Swamy",
    contactPhone: "+91 94407 11223",
    amenities: ["Weighbridge 40T", "Solar Powered Backup", "Fumigation Chambers"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 13. YSR Kadapa
  {
    id: "cs-kdp-001",
    facilityName: "Kadapa Banana & Tropical Fruits Cold Logistics Hub",
    registrationNumber: "AP-KDP-CS-2020-054",
    ownerId: "usr-owner-08",
    state: "Andhra Pradesh",
    district: "YSR Kadapa",
    mandal: "Pulivendula",
    village: "Pulivendula Town",
    address: "Agro Food Park, Pulivendula, YSR Kadapa 516390",
    coordinates: { lat: 14.4230, lng: 78.2310 },
    totalCapacityMT: 7000,
    availableCapacityMT: 1450,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Banana Holding Chamber 1", tempRange: "13°C to 15°C", capacityMT: 4000, availableMT: 850, suitableCommodities: ["Banana", "Papaya"] },
      { name: "Turmeric & General Chamber 2", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 600, suitableCommodities: ["Turmeric", "Sweet Orange"] }
    ],
    commoditiesSupported: ["Banana", "Papaya", "Turmeric", "Sweet Orange"],
    pricingPerMTMonth: 840,
    contactPerson: "T. Harinath Reddy",
    contactPhone: "+91 8568 244119",
    amenities: ["Ethylene Scrubbers", "Pallet Inverters", "Blast Cooler", "Reefer Docking Bays"],
    source: "AP Food Processing Society (APFPS)",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T15:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },
  {
    id: "cs-kdp-002",
    facilityName: "Proddatur Commercial Agro & Fruit Cold Store",
    registrationNumber: "AP-KDP-CS-2021-082",
    ownerId: "usr-owner-08",
    state: "Andhra Pradesh",
    district: "YSR Kadapa",
    mandal: "Proddatur",
    village: "Modameedapalle",
    address: "Jammalamadugu Road, Modameedapalle, Proddatur 516360",
    coordinates: { lat: 14.7520, lng: 78.5520 },
    totalCapacityMT: 6000,
    availableCapacityMT: 1800,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Banana & Papaya)", tempRange: "12°C to 15°C", capacityMT: 3500, availableMT: 1100, suitableCommodities: ["Banana", "Papaya"] },
      { name: "Chamber 2 (Turmeric & Citrus)", tempRange: "5°C to 9°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Turmeric", "Sweet Orange"] }
    ],
    commoditiesSupported: ["Banana", "Papaya", "Turmeric", "Sweet Orange"],
    pricingPerMTMonth: 820,
    contactPerson: "M. Subbarayudu",
    contactPhone: "+91 8564 252190",
    amenities: ["Weighbridge 50T", "Pre-cooling Unit", "Power Backup (150 KVA)"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T16:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 14. Prakasam
  {
    id: "cs-pkm-001",
    facilityName: "Ongole Spices & Horticultural Cold Chain Terminal",
    registrationNumber: "AP-PKM-CS-2019-029",
    ownerId: "usr-owner-02",
    state: "Andhra Pradesh",
    district: "Prakasam",
    mandal: "Ongole",
    village: "Pelluru",
    address: "NH-16 Bypass, Pelluru, Ongole 523272",
    coordinates: { lat: 15.5120, lng: 80.0450 },
    totalCapacityMT: 8000,
    availableCapacityMT: 2200,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Fresh Chilli & Spices)", tempRange: "4°C to 8°C", capacityMT: 4500, availableMT: 1300, suitableCommodities: ["Fresh Chilli"] },
      { name: "Chamber 2 (Sweet Orange & Tomato)", tempRange: "5°C to 10°C", capacityMT: 3500, availableMT: 900, suitableCommodities: ["Sweet Orange", "Tomato"] }
    ],
    commoditiesSupported: ["Fresh Chilli", "Sweet Orange", "Tomato", "Cashew"],
    pricingPerMTMonth: 800,
    contactPerson: "S. Venkateswarlu",
    contactPhone: "+91 8592 232110",
    amenities: ["Pre-cooling Unit", "Weighbridge 60T", "Solar Rooftop 200KW", "CCTV"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T12:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },
  {
    id: "cs-pkm-002",
    facilityName: "Markapur Agro & Sweet Orange Cold Hub",
    registrationNumber: "AP-PKM-CS-2022-073",
    ownerId: "usr-owner-02",
    state: "Andhra Pradesh",
    district: "Prakasam",
    mandal: "Markapur",
    village: "Dornala",
    address: "Srisailam Highway, Dornala, Markapur 523331",
    coordinates: { lat: 15.7350, lng: 79.2710 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1700,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Citrus Chamber", tempRange: "5°C to 8°C", capacityMT: 3000, availableMT: 1000, suitableCommodities: ["Sweet Orange"] },
      { name: "Chilli & Vegetable Chamber", tempRange: "3°C to 6°C", capacityMT: 2000, availableMT: 700, suitableCommodities: ["Fresh Chilli", "Tomato"] }
    ],
    commoditiesSupported: ["Sweet Orange", "Fresh Chilli", "Tomato"],
    pricingPerMTMonth: 770,
    contactPerson: "K. Chenna Kesava Rao",
    contactPhone: "+91 94409 33211",
    amenities: ["Weighbridge 40T", "Pre-cooling", "Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 15. Sri Potti Sriramulu Nellore
  {
    id: "cs-nlr-001",
    facilityName: "Nellore Citrus & Acid Lime Cold Logistics",
    registrationNumber: "AP-NLR-CS-2020-041",
    ownerId: "usr-owner-05",
    state: "Andhra Pradesh",
    district: "Sri Potti Sriramulu Nellore",
    mandal: "Nellore Urban",
    village: "Kallurpalli",
    address: "Autonagar Industrial Area, Kallurpalli, Nellore 524004",
    coordinates: { lat: 14.4480, lng: 79.9890 },
    totalCapacityMT: 7000,
    availableCapacityMT: 1900,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Acid Lime Precision Chamber", tempRange: "7°C to 10°C", capacityMT: 4000, availableMT: 1100, suitableCommodities: ["Acid Lime"] },
      { name: "Cashew & Produce Chamber", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 800, suitableCommodities: ["Cashew", "Vegetables"] }
    ],
    commoditiesSupported: ["Acid Lime", "Cashew", "Papaya", "Vegetables"],
    pricingPerMTMonth: 820,
    contactPerson: "P. Ravindra Naidu",
    contactPhone: "+91 861 2344567",
    amenities: ["Degreening Cells", "Waxing Line", "Weighbridge 50T", "Reefer Dock"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T14:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-nlr-002",
    facilityName: "Kavali Coastal Agro & Cashew Cold Depot",
    registrationNumber: "AP-NLR-CS-2022-099",
    ownerId: "usr-owner-05",
    state: "Andhra Pradesh",
    district: "Sri Potti Sriramulu Nellore",
    mandal: "Kavali",
    village: "Musunur",
    address: "NH-16 Chennai - Kolkata Highway, Musunur, Kavali 524201",
    coordinates: { lat: 14.9120, lng: 79.9920 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1500,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Cashew Zone", tempRange: "5°C to 9°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Cashew"] },
      { name: "Vegetable & Papaya Zone", tempRange: "8°C to 12°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Papaya", "Vegetables"] }
    ],
    commoditiesSupported: ["Cashew", "Papaya", "Acid Lime", "Vegetables"],
    pricingPerMTMonth: 790,
    contactPerson: "G. Sudhakar Reddy",
    contactPhone: "+91 94406 88910",
    amenities: ["De-humidifier", "Weighbridge 40T", "Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T15:00:00.000Z",
    lastVerified: "2026-09-27T08:30:00.000Z"
  },

  // 16. East Godavari
  {
    id: "cs-egd-001",
    facilityName: "Godavari Delta Banana & Mango Cold Terminal",
    registrationNumber: "AP-EGD-CS-2019-011",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "East Godavari",
    mandal: "Rajahmundry Urban",
    village: "Morampudi",
    address: "Morampudi Junction, NH-16, Rajahmundry 533106",
    coordinates: { lat: 17.0080, lng: 81.8120 },
    totalCapacityMT: 8500,
    availableCapacityMT: 2400,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Banana Ripening & Holding CA", tempRange: "12°C to 15°C", capacityMT: 4500, availableMT: 1300, suitableCommodities: ["Banana"] },
      { name: "Mango & Cocoa Cold Chamber", tempRange: "8°C to 12°C", capacityMT: 4000, availableMT: 1100, suitableCommodities: ["Mango", "Cocoa", "Cashew"] }
    ],
    commoditiesSupported: ["Banana", "Mango", "Cocoa", "Cashew"],
    pricingPerMTMonth: 860,
    contactPerson: "K. Satya Narayana Murthy",
    contactPhone: "+91 883 2466789",
    amenities: ["Ethylene Ripening (10 chambers)", "Weighbridge 60T", "Automated Pallet Conveyor"],
    source: "AP Food Processing Society",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T16:00:00.000Z",
    lastVerified: "2026-09-27T09:30:00.000Z"
  },
  {
    id: "cs-egd-002",
    facilityName: "Kovvur Agro Fresh & Cocoa Preservation Hub",
    registrationNumber: "AP-EGD-CS-2021-057",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "East Godavari",
    mandal: "Kovvur",
    village: "Dommeru",
    address: "Nidadavole Road, Dommeru, Kovvur 534350",
    coordinates: { lat: 17.0150, lng: 81.7280 },
    totalCapacityMT: 5500,
    availableCapacityMT: 1800,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Cocoa & Cashew Controlled Store", tempRange: "10°C to 14°C", capacityMT: 3000, availableMT: 1000, suitableCommodities: ["Cocoa", "Cashew"] },
      { name: "Banana & Mango Cell", tempRange: "8°C to 12°C", capacityMT: 2500, availableMT: 800, suitableCommodities: ["Banana", "Mango"] }
    ],
    commoditiesSupported: ["Cocoa", "Banana", "Cashew", "Mango"],
    pricingPerMTMonth: 820,
    contactPerson: "B. Venkanna Babu",
    contactPhone: "+91 98482 66551",
    amenities: ["Moisture Control", "Weighbridge 40T", "Power Backup 150 KVA"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 17. Kakinada
  {
    id: "cs-kkd-001",
    facilityName: "Kakinada Port Deep-Water Agro Cold Logistics",
    registrationNumber: "AP-KKD-CS-2020-025",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Kakinada",
    mandal: "Kakinada Urban",
    village: "Suryaraopeta",
    address: "Port Main Road, Suryaraopeta, Kakinada 533001",
    coordinates: { lat: 16.9920, lng: 82.2510 },
    totalCapacityMT: 9500,
    availableCapacityMT: 2900,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Export Fresh Produce Zone", tempRange: "4°C to 8°C", capacityMT: 5500, availableMT: 1700, suitableCommodities: ["Mango", "Banana"] },
      { name: "Cashew & Value-Added Products", tempRange: "6°C to 10°C", capacityMT: 4000, availableMT: 1200, suitableCommodities: ["Cashew", "Vegetables"] }
    ],
    commoditiesSupported: ["Mango", "Cashew", "Banana", "Vegetables"],
    pricingPerMTMonth: 880,
    contactPerson: "D. Suryanarayana Raju",
    contactPhone: "+91 884 2377890",
    amenities: ["Direct Port Reefer Access", "Bonded Warehouse", "Weighbridge 60T", "Blast Freezer"],
    source: "APEDA Certified Facility",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T17:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-kkd-002",
    facilityName: "Samalkota Cashew & Horticultural Cold Store",
    registrationNumber: "AP-KKD-CS-2022-088",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Kakinada",
    mandal: "Samalkota",
    village: "Peddapuram",
    address: "ADB Road, Peddapuram Industrial Zone, Samalkota 533440",
    coordinates: { lat: 17.0510, lng: 82.1720 },
    totalCapacityMT: 6000,
    availableCapacityMT: 1600,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Cashew Processing & Holding Chamber", tempRange: "5°C to 9°C", capacityMT: 3500, availableMT: 900, suitableCommodities: ["Cashew"] },
      { name: "Mango & Tropical Fruit Chamber", tempRange: "8°C to 12°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Mango", "Banana"] }
    ],
    commoditiesSupported: ["Cashew", "Mango", "Banana", "Vegetables"],
    pricingPerMTMonth: 810,
    contactPerson: "V. Subba Rao",
    contactPhone: "+91 94401 77890",
    amenities: ["De-humidifier", "Weighbridge 50T", "Power Backup 200 KVA"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T14:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 18. Dr. B.R. Ambedkar Konaseema
  {
    id: "cs-kns-001",
    facilityName: "Konaseema Banana & Coconut Cold Logistics Terminal",
    registrationNumber: "AP-KNS-CS-2021-037",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "Dr. B.R. Ambedkar Konaseema",
    mandal: "Amalapuram",
    village: "Bandarulanka",
    address: "Bandarulanka Road, Amalapuram 533201",
    coordinates: { lat: 16.5820, lng: 82.0120 },
    totalCapacityMT: 7000,
    availableCapacityMT: 2100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Banana Controlled Humidity Cell", tempRange: "12°C to 15°C", capacityMT: 4500, availableMT: 1400, suitableCommodities: ["Banana", "Papaya"] },
      { name: "Cashew & Vegetables Cell", tempRange: "4°C to 8°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Cashew", "Vegetables"] }
    ],
    commoditiesSupported: ["Banana", "Cashew", "Papaya", "Vegetables"],
    pricingPerMTMonth: 820,
    contactPerson: "M. Ramakrishna Raju",
    contactPhone: "+91 8856 233441",
    amenities: ["Ethylene Scrubbers", "Pre-cooling Units", "Weighbridge 50T"],
    source: "AP Food Processing Society",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T12:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },
  {
    id: "cs-kns-002",
    facilityName: "Ravulapalem Horticultural Fresh Cold Hub",
    registrationNumber: "AP-KNS-CS-2022-094",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "Dr. B.R. Ambedkar Konaseema",
    mandal: "Ravulapalem",
    village: "Kothapeta",
    address: "NH-16 River Bridge Approach, Ravulapalem 533238",
    coordinates: { lat: 16.7490, lng: 81.8420 },
    totalCapacityMT: 5500,
    availableCapacityMT: 1700,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Banana Ripening Chamber", tempRange: "13°C to 16°C", capacityMT: 3500, availableMT: 1100, suitableCommodities: ["Banana"] },
      { name: "Tropical Fruit & Veg Chamber", tempRange: "6°C to 10°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Papaya", "Vegetables"] }
    ],
    commoditiesSupported: ["Banana", "Papaya", "Cashew", "Vegetables"],
    pricingPerMTMonth: 800,
    contactPerson: "P. Trinadha Rao",
    contactPhone: "+91 94418 55234",
    amenities: ["Direct Highway Loading Dock", "Weighbridge 40T", "Automated Dataloggers"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T16:00:00.000Z",
    lastVerified: "2026-09-27T08:30:00.000Z"
  },

  // 19. West Godavari
  {
    id: "cs-wgd-001",
    facilityName: "Tadepalligudem Agro Wholesale Cold Terminal",
    registrationNumber: "AP-WGD-CS-2018-028",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "West Godavari",
    mandal: "Tadepalligudem",
    village: "Pentapadu",
    address: "NH-16 Industrial Corridor, Pentapadu, Tadepalligudem 534101",
    coordinates: { lat: 16.8120, lng: 81.5280 },
    totalCapacityMT: 9000,
    availableCapacityMT: 2600,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Banana & Multi-Fruit CA Unit", tempRange: "10°C to 14°C", capacityMT: 5000, availableMT: 1500, suitableCommodities: ["Banana", "Guava"] },
      { name: "Cocoa & Vegetable Cold Cell", tempRange: "4°C to 8°C", capacityMT: 4000, availableMT: 1100, suitableCommodities: ["Cocoa", "Vegetables"] }
    ],
    commoditiesSupported: ["Banana", "Guava", "Cocoa", "Vegetables"],
    pricingPerMTMonth: 840,
    contactPerson: "N. Venkateswara Rao",
    contactPhone: "+91 8818 224455",
    amenities: ["Pre-cooling Unit", "Weighbridge 60T", "Automated Sorting", "Power Backup (250 KVA)"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T15:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-wgd-002",
    facilityName: "Bhimavaram Delta Agro & Marine Cold Storage",
    registrationNumber: "AP-WGD-CS-2020-072",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "West Godavari",
    mandal: "Bhimavaram",
    village: "Rayalam",
    address: "Rayalam Bypass, Bhimavaram 534208",
    coordinates: { lat: 16.5410, lng: 81.5250 },
    totalCapacityMT: 7000,
    availableCapacityMT: 2000,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Guava & Fruit Holding Zone", tempRange: "8°C to 12°C", capacityMT: 4000, availableMT: 1200, suitableCommodities: ["Guava", "Banana"] },
      { name: "Fresh Vegetables Cell", tempRange: "2°C to 6°C", capacityMT: 3000, availableMT: 800, suitableCommodities: ["Vegetables"] }
    ],
    commoditiesSupported: ["Guava", "Banana", "Vegetables", "Cocoa"],
    pricingPerMTMonth: 830,
    contactPerson: "K. Satish Varma",
    contactPhone: "+91 8816 235567",
    amenities: ["Blast Chiller", "Weighbridge 50T", "Pre-cooling Dock"],
    source: "AP Food Processing Society",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  {
    id: "cs-wgd-003",
    facilityName: "Tanuku Fruit & Vegetable Cold Chain",
    registrationNumber: "AP-WGD-CS-2022-099",
    ownerId: "usr-owner-04",
    state: "Andhra Pradesh",
    district: "West Godavari",
    mandal: "Tanuku",
    village: "Tetali",
    address: "NH-16 By-pass, Tetali, Tanuku 534211",
    coordinates: { lat: 16.7550, lng: 81.6820 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1400,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Banana & Guava)", tempRange: "8°C to 12°C", capacityMT: 3000, availableMT: 800, suitableCommodities: ["Banana", "Guava"] },
      { name: "Chamber 2 (Cocoa & Produce)", tempRange: "4°C to 8°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Cocoa", "Vegetables"] }
    ],
    commoditiesSupported: ["Banana", "Guava", "Cocoa", "Vegetables"],
    pricingPerMTMonth: 810,
    contactPerson: "P. Ranga Rao",
    contactPhone: "+91 94403 44190",
    amenities: ["Weighbridge 40T", "Pre-cooling Units", "Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T14:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },

  // 20. Eluru
  {
    id: "cs-elr-001",
    facilityName: "Eluru District Agro Preservation Hub",
    registrationNumber: "AP-ELR-CS-2020-034",
    ownerId: "usr-owner-03",
    state: "Andhra Pradesh",
    district: "Eluru",
    mandal: "Eluru Urban",
    village: "Sanivarapupeta",
    address: "Bypass Road, Sanivarapupeta, Eluru 534003",
    coordinates: { lat: 16.7150, lng: 81.1020 },
    totalCapacityMT: 7500,
    availableCapacityMT: 2200,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Oil Palm & Cocoa)", tempRange: "10°C to 14°C", capacityMT: 4500, availableMT: 1300, suitableCommodities: ["Cocoa", "Banana"] },
      { name: "Chamber 2 (Mango & Vegetables)", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Mango", "Vegetables"] }
    ],
    commoditiesSupported: ["Cocoa", "Banana", "Mango", "Oil Palm"],
    pricingPerMTMonth: 800,
    contactPerson: "Ch. Venkanna Chowdary",
    contactPhone: "+91 8812 245566",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Solar Power Backup (150 KW)"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T16:00:00.000Z",
    lastVerified: "2026-09-27T09:30:00.000Z"
  },
  {
    id: "cs-elr-002",
    facilityName: "Jangareddigudem Horticulture Cold Terminal",
    registrationNumber: "AP-ELR-CS-2022-081",
    ownerId: "usr-owner-03",
    state: "Andhra Pradesh",
    district: "Eluru",
    mandal: "Jangareddigudem",
    village: "Chintalapudi Road",
    address: "State Highway 42, Jangareddigudem 534447",
    coordinates: { lat: 17.1250, lng: 81.2950 },
    totalCapacityMT: 5500,
    availableCapacityMT: 1700,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Cocoa & Banana)", tempRange: "8°C to 12°C", capacityMT: 3500, availableMT: 1100, suitableCommodities: ["Cocoa", "Banana"] },
      { name: "Chamber 2 (Mango & Produce)", tempRange: "4°C to 8°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Mango", "Vegetables"] }
    ],
    commoditiesSupported: ["Cocoa", "Banana", "Mango", "Vegetables"],
    pricingPerMTMonth: 780,
    contactPerson: "K. Mohan Babu",
    contactPhone: "+91 94408 22199",
    amenities: ["Weighbridge 40T", "Pre-cooling Dock", "Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T12:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 21. Visakhapatnam
  {
    id: "cs-vsp-001",
    facilityName: "Visakha Coastal Cold Chain & Reefer Logistics",
    registrationNumber: "AP-VSP-CS-2015-003",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    mandal: "Visakhapatnam Urban",
    village: "Gajuwaka",
    address: "Industrial Development Area, Gajuwaka, Visakhapatnam 530026",
    coordinates: { lat: 17.6980, lng: 83.1950 },
    totalCapacityMT: 11000,
    availableCapacityMT: 3900,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Dry Spices & Cashew Zone", tempRange: "5°C to 10°C", capacityMT: 6000, availableMT: 2200, suitableCommodities: ["Cashew", "Coffee", "Turmeric"] },
      { name: "Vegetables & Local Produce Zone", tempRange: "2°C to 6°C", capacityMT: 5000, availableMT: 1700, suitableCommodities: ["Tomato", "Vegetables", "Banana"] }
    ],
    commoditiesSupported: ["Cashew", "Tomato", "Banana", "Turmeric"],
    pricingPerMTMonth: 880,
    contactPerson: "K. Appa Rao",
    contactPhone: "+91 891 2755441",
    amenities: ["Port Proximity 8km", "Bonded Warehouse", "Container Reefer Plugs 40 units"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T16:00:00.000Z",
    lastVerified: "2026-09-26T14:00:00.000Z"
  },
  {
    id: "cs-vsp-002",
    facilityName: "Anandapuram Multi-Crop Urban Transit Cold Hub",
    registrationNumber: "AP-VSP-CS-2021-061",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    mandal: "Anandapuram",
    village: "Padmanabham",
    address: "NH-16 Outer Ring Corridor, Anandapuram, Visakhapatnam 530052",
    coordinates: { lat: 17.9050, lng: 83.3980 },
    totalCapacityMT: 6500,
    availableCapacityMT: 1800,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Vegetable Chilling Cell", tempRange: "2°C to 5°C", capacityMT: 4000, availableMT: 1100, suitableCommodities: ["Vegetables", "Tomato"] },
      { name: "Cashew & Fruit Cell", tempRange: "6°C to 10°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Cashew", "Papaya"] }
    ],
    commoditiesSupported: ["Vegetables", "Cashew", "Tomato", "Papaya"],
    pricingPerMTMonth: 850,
    contactPerson: "B. Jagannadha Rao",
    contactPhone: "+91 94401 99882",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Automated Dataloggers"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T11:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },

  // 22. Anakapalli
  {
    id: "cs-akp-001",
    facilityName: "Anakapalli Agro Terminal & Jaggery-Fruit Cold Store",
    registrationNumber: "AP-AKP-CS-2020-043",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Anakapalli",
    mandal: "Anakapalli",
    village: "Thummapala",
    address: "Thummapala Industrial Area, Anakapalli 531001",
    coordinates: { lat: 17.6950, lng: 83.0080 },
    totalCapacityMT: 7000,
    availableCapacityMT: 2100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Tomato & Vegetables)", tempRange: "3°C to 7°C", capacityMT: 4000, availableMT: 1200, suitableCommodities: ["Tomato", "Vegetables"] },
      { name: "Chamber 2 (Mango & Cashew)", tempRange: "6°C to 10°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Mango", "Cashew"] }
    ],
    commoditiesSupported: ["Tomato", "Cashew", "Mango", "Vegetables"],
    pricingPerMTMonth: 820,
    contactPerson: "G. Varahala Naidu",
    contactPhone: "+91 8924 221190",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Power Backup (150 KVA)"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T14:00:00.000Z",
    lastVerified: "2026-09-27T08:30:00.000Z"
  },
  {
    id: "cs-akp-002",
    facilityName: "Chodavaram Organic & Agro Cold Depot",
    registrationNumber: "AP-AKP-CS-2022-095",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Anakapalli",
    mandal: "Chodavaram",
    village: "K.Kotapadu",
    address: "SH-9 Highway, K.Kotapadu, Chodavaram 531036",
    coordinates: { lat: 17.8350, lng: 82.9480 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1600,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Vegetable Cell", tempRange: "2°C to 6°C", capacityMT: 3000, availableMT: 1000, suitableCommodities: ["Tomato", "Vegetables"] },
      { name: "Cashew & Fruit Cell", tempRange: "7°C to 11°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Cashew", "Mango"] }
    ],
    commoditiesSupported: ["Tomato", "Vegetables", "Cashew", "Mango"],
    pricingPerMTMonth: 790,
    contactPerson: "D. Sanyasi Rao",
    contactPhone: "+91 94407 66554",
    amenities: ["Weighbridge 40T", "Pre-cooling Fans", "Solar Rooftop 100 KW"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T16:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 23. Alluri Sitharama Raju
  {
    id: "cs-asr-001",
    facilityName: "Araku Valley Hill Produce & Organic Coffee Cold Store",
    registrationNumber: "AP-ASR-CS-2021-016",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Alluri Sitharama Raju",
    mandal: "Araku Valley",
    village: "Dumbriguda",
    address: "Araku - Paderu Ghat Road, Dumbriguda, Araku Valley 531149",
    coordinates: { lat: 18.3280, lng: 82.8790 },
    totalCapacityMT: 4000,
    availableCapacityMT: 1200,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Organic Coffee & Pepper Cell", tempRange: "12°C to 16°C", capacityMT: 2500, availableMT: 800, suitableCommodities: ["Coffee", "Black Pepper"] },
      { name: "Ginger & Turmeric Cell", tempRange: "6°C to 10°C", capacityMT: 1500, availableMT: 400, suitableCommodities: ["Ginger", "Turmeric"] }
    ],
    commoditiesSupported: ["Coffee", "Turmeric", "Ginger", "Black Pepper"],
    pricingPerMTMonth: 850,
    contactPerson: "P. Somalingam Dora",
    contactPhone: "+91 8936 249910",
    amenities: ["Solar-Diesel Hybrid Generator", "De-humidifier", "Weighbridge 30T", "Tribal FPO Dedicated Bays"],
    source: "GCC (Girijan Co-operative Corporation) & AP Horti Dept",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T15:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },
  {
    id: "cs-asr-002",
    facilityName: "Paderu Tribal Agency Horticultural Cold Depot",
    registrationNumber: "AP-ASR-CS-2022-074",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Alluri Sitharama Raju",
    mandal: "Paderu",
    village: "G.Madugula",
    address: "Main Agency Road, Paderu 531024",
    coordinates: { lat: 18.0860, lng: 82.6710 },
    totalCapacityMT: 3500,
    availableCapacityMT: 1100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Ginger & Turmeric Holding Chamber", tempRange: "7°C to 10°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Ginger", "Turmeric"] },
      { name: "Coffee & Spices Chamber", tempRange: "12°C to 15°C", capacityMT: 1500, availableMT: 500, suitableCommodities: ["Coffee"] }
    ],
    commoditiesSupported: ["Turmeric", "Ginger", "Coffee", "Black Pepper"],
    pricingPerMTMonth: 800,
    contactPerson: "K. Balaraju",
    contactPhone: "+91 94412 88712",
    amenities: ["Pre-cooling Unit", "Weighbridge 30T", "Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 24. Vizianagaram
  {
    id: "cs-vzm-001",
    facilityName: "Vizianagaram Agro & Mango Export Cold Chain",
    registrationNumber: "AP-VZM-CS-2019-021",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Vizianagaram",
    mandal: "Vizianagaram",
    village: "Dharmapuri",
    address: "NH-26 Raipur Highway, Dharmapuri, Vizianagaram 535002",
    coordinates: { lat: 18.1180, lng: 83.3980 },
    totalCapacityMT: 7000,
    availableCapacityMT: 2100,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Mango & Tropical Fruit Chamber", tempRange: "8°C to 12°C", capacityMT: 4000, availableMT: 1200, suitableCommodities: ["Mango", "Banana"] },
      { name: "Cashew & Tomato Cell", tempRange: "4°C to 8°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Cashew", "Tomato"] }
    ],
    commoditiesSupported: ["Mango", "Cashew", "Tomato", "Banana"],
    pricingPerMTMonth: 810,
    contactPerson: "S. Appala Naidu",
    contactPhone: "+91 8922 278890",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Power Backup (200 KVA)", "Grading Table"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T16:00:00.000Z",
    lastVerified: "2026-09-27T10:00:00.000Z"
  },
  {
    id: "cs-vzm-002",
    facilityName: "Bobbili Horticultural & Cashew Cold Depot",
    registrationNumber: "AP-VZM-CS-2021-085",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Vizianagaram",
    mandal: "Bobbili",
    village: "Badangi",
    address: "Bobbili Industrial Growth Center, Bobbili 535558",
    coordinates: { lat: 18.5720, lng: 83.3650 },
    totalCapacityMT: 5000,
    availableCapacityMT: 1500,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Cashew Chamber", tempRange: "5°C to 9°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Cashew"] },
      { name: "Mango & Produce Chamber", tempRange: "8°C to 12°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Mango", "Banana"] }
    ],
    commoditiesSupported: ["Cashew", "Mango", "Banana", "Tomato"],
    pricingPerMTMonth: 780,
    contactPerson: "M. Satyanarayana",
    contactPhone: "+91 94405 11982",
    amenities: ["Weighbridge 40T", "Pre-cooling Units", "Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T14:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 25. Parvathipuram Manyam
  {
    id: "cs-pvm-001",
    facilityName: "Manyam Tribal & Cashew Agro Cold Terminal",
    registrationNumber: "AP-PVM-CS-2021-032",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Parvathipuram Manyam",
    mandal: "Parvathipuram",
    village: "Seethanagaram",
    address: "SH-4 Raipur Road, Seethanagaram, Parvathipuram 535501",
    coordinates: { lat: 18.7790, lng: 83.4320 },
    totalCapacityMT: 5500,
    availableCapacityMT: 1700,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Cashew & Turmeric Chamber", tempRange: "5°C to 9°C", capacityMT: 3500, availableMT: 1100, suitableCommodities: ["Cashew", "Turmeric"] },
      { name: "Mango & Fruit Cell", tempRange: "8°C to 12°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Mango", "Banana"] }
    ],
    commoditiesSupported: ["Cashew", "Mango", "Banana", "Turmeric"],
    pricingPerMTMonth: 790,
    contactPerson: "V. Jagannadham",
    contactPhone: "+91 8963 221145",
    amenities: ["Pre-cooling Unit", "Weighbridge 40T", "Solar Powered Backup 120 KW"],
    source: "AP Food Processing Society",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T12:00:00.000Z",
    lastVerified: "2026-09-27T09:00:00.000Z"
  },
  {
    id: "cs-pvm-002",
    facilityName: "Salur Agro Fresh & Spices Cold Depot",
    registrationNumber: "AP-PVM-CS-2022-069",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Parvathipuram Manyam",
    mandal: "Salur",
    village: "Makkuva",
    address: "Ghat Road, Makkuva, Salur 535591",
    coordinates: { lat: 18.5280, lng: 83.2120 },
    totalCapacityMT: 4500,
    availableCapacityMT: 1300,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Spices & Cashew Chamber", tempRange: "5°C to 9°C", capacityMT: 2500, availableMT: 700, suitableCommodities: ["Turmeric", "Cashew"] },
      { name: "Fresh Produce Chamber", tempRange: "8°C to 12°C", capacityMT: 2000, availableMT: 600, suitableCommodities: ["Mango", "Banana"] }
    ],
    commoditiesSupported: ["Cashew", "Turmeric", "Mango", "Banana"],
    pricingPerMTMonth: 770,
    contactPerson: "Ch. Suryanarayana",
    contactPhone: "+91 94409 77123",
    amenities: ["Weighbridge 40T", "Pre-cooling Fans", "Power Backup"],
    source: "AP Horticulture Department",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T11:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },

  // 26. Srikakulam
  {
    id: "cs-skl-001",
    facilityName: "Palasa Cashew & Multi-Crop Cold Logistics Hub",
    registrationNumber: "AP-SKL-CS-2018-014",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Srikakulam",
    mandal: "Palasa-Kasibugga",
    village: "Palasa Town",
    address: "Cashew Industrial Zone, NH-16, Palasa 532221",
    coordinates: { lat: 18.7710, lng: 84.4150 },
    totalCapacityMT: 8000,
    availableCapacityMT: 2400,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Cashew Processing & Holding CA", tempRange: "4°C to 8°C", capacityMT: 5000, availableMT: 1500, suitableCommodities: ["Cashew"] },
      { name: "Mango & Tropical Produce Chamber", tempRange: "8°C to 12°C", capacityMT: 3000, availableMT: 900, suitableCommodities: ["Mango", "Banana"] }
    ],
    commoditiesSupported: ["Cashew", "Mango", "Banana", "Tomato"],
    pricingPerMTMonth: 820,
    contactPerson: "K. Mohan Rao",
    contactPhone: "+91 8945 241190",
    amenities: ["Moisture Control De-humidifiers", "Weighbridge 60T", "Automated Packaging Lines", "Genset 250 KVA"],
    source: "AP Cashew Board & AP Horticulture Dept",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-26T17:00:00.000Z",
    lastVerified: "2026-09-27T10:30:00.000Z"
  },
  {
    id: "cs-skl-002",
    facilityName: "Srikakulam Central Horticultural Cold Store",
    registrationNumber: "AP-SKL-CS-2021-073",
    ownerId: "usr-owner-10",
    state: "Andhra Pradesh",
    district: "Srikakulam",
    mandal: "Srikakulam",
    village: "Singupuram",
    address: "NH-16 By-pass Road, Singupuram, Srikakulam 532001",
    coordinates: { lat: 18.3010, lng: 83.9010 },
    totalCapacityMT: 6000,
    availableCapacityMT: 1900,
    operatingStatus: "Active",
    temperatureZones: [
      { name: "Chamber 1 (Cashew & Tomato)", tempRange: "4°C to 8°C", capacityMT: 3500, availableMT: 1100, suitableCommodities: ["Cashew", "Tomato"] },
      { name: "Chamber 2 (Banana & Mango)", tempRange: "8°C to 12°C", capacityMT: 2500, availableMT: 800, suitableCommodities: ["Banana", "Mango"] }
    ],
    commoditiesSupported: ["Cashew", "Tomato", "Banana", "Mango"],
    pricingPerMTMonth: 790,
    contactPerson: "P. Trinatha Naidu",
    contactPhone: "+91 8942 223388",
    amenities: ["Pre-cooling Unit", "Weighbridge 50T", "Power Backup (150 KVA)"],
    source: "AP State Warehouse Regulatory Authority",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-25T16:00:00.000Z",
    lastVerified: "2026-09-27T08:30:00.000Z"
  }
];

// Expanded APMC Mandis across key districts
const COMPREHENSIVE_MARKETS = [
  // Guntur
  {
    id: "mkt-gnt-001",
    marketName: "Guntur Agricultural Market Yard (Asia's Largest Chilli & Spices Yard)",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Guntur",
    mandal: "Guntur Urban",
    coordinates: { lat: 16.2980, lng: 80.4450 },
    majorCommodities: ["Fresh Chilli", "Turmeric", "Cotton"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Palnadu
  {
    id: "mkt-pln-001",
    marketName: "Narasaraopet Commercial & Chilli Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Palnadu",
    mandal: "Narasaraopet",
    coordinates: { lat: 16.2410, lng: 80.0590 },
    majorCommodities: ["Fresh Chilli", "Tomato", "Lime"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Bapatla
  {
    id: "mkt-bpt-001",
    marketName: "Bapatla Banana & Cashew Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Bapatla",
    mandal: "Bapatla",
    coordinates: { lat: 15.9080, lng: 80.4720 },
    majorCommodities: ["Banana", "Fresh Chilli", "Cashew"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Krishna
  {
    id: "mkt-kri-001",
    marketName: "Nuzvid Royal Mango Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Krishna",
    mandal: "Nuzvid",
    coordinates: { lat: 16.7890, lng: 80.8520 },
    majorCommodities: ["Mango", "Guava", "Banana"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // NTR
  {
    id: "mkt-ntr-001",
    marketName: "Nunna Mango APMC Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "NTR",
    mandal: "Vijayawada Rural",
    coordinates: { lat: 16.5840, lng: 80.6950 },
    majorCommodities: ["Mango", "Banana", "Acid Lime"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Chittoor
  {
    id: "mkt-ctr-001",
    marketName: "Palamaner Tomato & Fruit Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Chittoor",
    mandal: "Palamaner",
    coordinates: { lat: 13.2080, lng: 78.7610 },
    majorCommodities: ["Tomato", "Mango", "Banana"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Tirupati
  {
    id: "mkt-tpt-001",
    marketName: "Srikalahasti Citrus & Agro Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Tirupati",
    mandal: "Srikalahasti",
    coordinates: { lat: 13.7550, lng: 79.7110 },
    majorCommodities: ["Lime", "Mango", "Tomato"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Annamayya
  {
    id: "mkt-amm-001",
    marketName: "Madanapalle Tomato Special Market Committee",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Annamayya",
    mandal: "Madanapalle",
    coordinates: { lat: 13.5560, lng: 78.5030 },
    majorCommodities: ["Tomato", "Mango", "Papaya"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Ananthapuramu
  {
    id: "mkt-atp-001",
    marketName: "Tadipatri Sweet Orange & Citrus Market",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Ananthapuramu",
    mandal: "Tadipatri",
    coordinates: { lat: 14.9150, lng: 78.0190 },
    majorCommodities: ["Sweet Orange", "Pomegranate", "Banana"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Sri Sathya Sai
  {
    id: "mkt-sss-001",
    marketName: "Hindupur Commercial Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Sri Sathya Sai",
    mandal: "Hindupur",
    coordinates: { lat: 13.8350, lng: 77.4980 },
    majorCommodities: ["Sweet Orange", "Mango", "Banana"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Kurnool
  {
    id: "mkt-knl-001",
    marketName: "Kurnool Commercial & Horticultural Crops Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Kurnool",
    mandal: "Kurnool Urban",
    coordinates: { lat: 15.8230, lng: 78.0410 },
    majorCommodities: ["Fresh Chilli", "Tomato", "Sweet Orange"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Nandyal
  {
    id: "mkt-ndl-001",
    marketName: "Nandyal Turmeric & Commercial Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Nandyal",
    mandal: "Nandyal",
    coordinates: { lat: 15.4890, lng: 78.4950 },
    majorCommodities: ["Turmeric", "Fresh Chilli", "Banana"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // YSR Kadapa
  {
    id: "mkt-kdp-001",
    marketName: "Pulivendula Horticulture & Banana Terminal",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "YSR Kadapa",
    mandal: "Pulivendula",
    coordinates: { lat: 14.4260, lng: 78.2340 },
    majorCommodities: ["Banana", "Papaya", "Sweet Orange"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Prakasam
  {
    id: "mkt-pkm-001",
    marketName: "Ongole Commercial Spices & Chilli Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Prakasam",
    mandal: "Ongole",
    coordinates: { lat: 15.5180, lng: 80.0520 },
    majorCommodities: ["Fresh Chilli", "Tomato", "Sweet Orange"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Sri Potti Sriramulu Nellore
  {
    id: "mkt-nlr-001",
    marketName: "Podalakur Acid Lime & Citrus Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Sri Potti Sriramulu Nellore",
    mandal: "Podalakur",
    coordinates: { lat: 14.4520, lng: 79.9950 },
    majorCommodities: ["Acid Lime", "Cashew", "Papaya"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // East Godavari
  {
    id: "mkt-egd-001",
    marketName: "Rajahmundry Banana & Fruit Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "East Godavari",
    mandal: "Rajahmundry Urban",
    coordinates: { lat: 17.0120, lng: 81.8190 },
    majorCommodities: ["Banana", "Cashew", "Mango"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Kakinada
  {
    id: "mkt-kkd-001",
    marketName: "Samalkota Cashew & Agricultural Market",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Kakinada",
    mandal: "Samalkota",
    coordinates: { lat: 17.0580, lng: 82.1790 },
    majorCommodities: ["Cashew", "Mango", "Banana"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Konaseema
  {
    id: "mkt-kns-001",
    marketName: "Ravulapalem Banana Mega Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Dr. B.R. Ambedkar Konaseema",
    mandal: "Ravulapalem",
    coordinates: { lat: 16.7550, lng: 81.8490 },
    majorCommodities: ["Banana", "Papaya", "Cashew"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // West Godavari
  {
    id: "mkt-wgd-001",
    marketName: "Tadepalligudem Wholesale Agro Market",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "West Godavari",
    mandal: "Tadepalligudem",
    coordinates: { lat: 16.8180, lng: 81.5340 },
    majorCommodities: ["Banana", "Guava", "Cocoa"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Eluru
  {
    id: "mkt-elr-001",
    marketName: "Eluru Agricultural Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Eluru",
    mandal: "Eluru Urban",
    coordinates: { lat: 16.7210, lng: 81.1090 },
    majorCommodities: ["Cocoa", "Banana", "Mango"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Visakhapatnam
  {
    id: "mkt-vsp-001",
    marketName: "Visakhapatnam Regional Agro Produce Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    mandal: "Visakhapatnam Urban",
    coordinates: { lat: 17.7050, lng: 83.2010 },
    majorCommodities: ["Cashew", "Vegetables", "Tomato"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Anakapalli
  {
    id: "mkt-akp-001",
    marketName: "Anakapalli Commercial Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Anakapalli",
    mandal: "Anakapalli",
    coordinates: { lat: 17.7010, lng: 83.0140 },
    majorCommodities: ["Tomato", "Cashew", "Mango"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // ASR
  {
    id: "mkt-asr-001",
    marketName: "Araku Valley Organic Produce Terminal",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Alluri Sitharama Raju",
    mandal: "Araku Valley",
    coordinates: { lat: 18.3340, lng: 82.8850 },
    majorCommodities: ["Coffee", "Turmeric", "Ginger"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Vizianagaram
  {
    id: "mkt-vzm-001",
    marketName: "Vizianagaram Horticultural Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Vizianagaram",
    mandal: "Vizianagaram",
    coordinates: { lat: 18.1240, lng: 83.4040 },
    majorCommodities: ["Mango", "Cashew", "Tomato"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Parvathipuram Manyam
  {
    id: "mkt-pvm-001",
    marketName: "Parvathipuram Agency Produce Market",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Parvathipuram Manyam",
    mandal: "Parvathipuram",
    coordinates: { lat: 18.7840, lng: 83.4380 },
    majorCommodities: ["Cashew", "Mango", "Turmeric"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  },
  // Srikakulam
  {
    id: "mkt-skl-001",
    marketName: "Palasa Cashew Special Market Yard",
    marketType: "APMC / RMC Yard",
    state: "Andhra Pradesh",
    district: "Srikakulam",
    mandal: "Palasa-Kasibugga",
    coordinates: { lat: 18.7770, lng: 84.4210 },
    majorCommodities: ["Cashew", "Mango", "Tomato"],
    source: "APAMB e-NAM",
    sourceType: "Government",
    sourceLastUpdated: "2026-09-27T06:00:00.000Z",
    lastVerified: "2026-09-27T08:00:00.000Z"
  }
];

export { COMPREHENSIVE_COLD_STORAGES, COMPREHENSIVE_MARKETS };
