// 26 Strategic Potential New Cold Storage Locations across Andhra Pradesh
// Calculated by Spatial Deficit, Farm Catchment Clustering & Perishability Algorithms

export const COMPREHENSIVE_POTENTIAL_LOCATIONS = [
  // 1. Annamayya - Critical
  {
    id: "pot-amm-001",
    clusterName: "Madanapalle - Tamballapalle Mega Tomato Cold Hub",
    district: "Annamayya",
    mandal: "Madanapalle",
    suggestedCoordinates: { lat: 13.5820, lng: 78.4710 },
    priorityScore: 98,
    urgencyLevel: "Critical Priority",
    localProduceAtRiskMTPerYear: 185000,
    primaryTargetCommodities: ["Tomato", "Papaya", "Capsicum"],
    distanceToNearestExistingColdStorageKm: 28.5,
    recommendedCapacityMT: 10000,
    recommendedChamberType: "Controlled Atmosphere (CA) Multi-Chamber with Hydro-cooling & Sorting lines",
    estimatedCapexCroresINR: 14.5,
    paybackPeriodYears: 3.8,
    connectivity: "Direct access to NH-71 & NH-42 corridor to Bengaluru & Chennai markets",
    rationale: "Asia's largest tomato production belt experiences extreme price collapse during harvest gluts (prices dropping to Rs. 2-3/kg). Zero public CA cold storage within 25km radius causes up to 32% post-harvest spoilage.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 2. Sri Potti Sriramulu Nellore - Critical
  {
    id: "pot-nlr-001",
    clusterName: "Podalakur - Rapur Acid Lime & Citrus Mega Preservation Hub",
    district: "Sri Potti Sriramulu Nellore",
    mandal: "Podalakur",
    suggestedCoordinates: { lat: 14.3820, lng: 79.7210 },
    priorityScore: 95,
    urgencyLevel: "Critical Priority",
    localProduceAtRiskMTPerYear: 165000,
    primaryTargetCommodities: ["Acid Lime", "Cashew", "Papaya"],
    distanceToNearestExistingColdStorageKm: 42.0,
    recommendedCapacityMT: 8500,
    recommendedChamberType: "Controlled Humidity (85-90%) & Degreening Multi-Chamber Facility",
    estimatedCapexCroresINR: 12.2,
    paybackPeriodYears: 3.9,
    connectivity: "State Highway connecting Nellore and Venkatagiri to NH-16 corridor",
    rationale: "Podalakur and Rapur produce over 60% of Andhra Pradesh's acid lime. In summer months, skin yellowing and dehydration reduce export value by 45% within 48 hours of plucking without immediate cold staging.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 3. Kurnool - Critical
  {
    id: "pot-knl-001",
    clusterName: "Adoni - Yemmiganur Multi-Commodity Cold Park",
    district: "Kurnool",
    mandal: "Adoni",
    suggestedCoordinates: { lat: 15.6320, lng: 77.2750 },
    priorityScore: 94,
    urgencyLevel: "Critical Priority",
    localProduceAtRiskMTPerYear: 142000,
    primaryTargetCommodities: ["Fresh Chilli", "Tomato", "Sweet Orange"],
    distanceToNearestExistingColdStorageKm: 42.0,
    recommendedCapacityMT: 8000,
    recommendedChamberType: "Ventilated Precision Multi-Chamber (4-10°C) with Pre-cooling",
    estimatedCapexCroresINR: 11.8,
    paybackPeriodYears: 4.1,
    connectivity: "State Highway 24 connecting Adoni Industrial bypass and railway freight terminal",
    rationale: "Western Kurnool produces over 140,000 MT of commercial fresh chillies and tomatoes. Severe deficit forces smallholders to sell at sub-optimal farmgate rates, resulting in up to 28% post-harvest decay.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 4. NTR - Critical
  {
    id: "pot-ntr-001",
    clusterName: "Mylavaram - Tiruvuru Mango Packhouse & CA Facility",
    district: "NTR",
    mandal: "Mylavaram",
    suggestedCoordinates: { lat: 16.7910, lng: 80.6420 },
    priorityScore: 93,
    urgencyLevel: "Critical Priority",
    localProduceAtRiskMTPerYear: 152000,
    primaryTargetCommodities: ["Mango", "Papaya", "Fresh Chilli"],
    distanceToNearestExistingColdStorageKm: 32.0,
    recommendedCapacityMT: 9000,
    recommendedChamberType: "APEDA-Certified CA Chambers with Vapour Heat Treatment (VHT) Line",
    estimatedCapexCroresINR: 13.5,
    paybackPeriodYears: 3.7,
    connectivity: "NH-30 linking Vijayawada and Bhadrachalam",
    rationale: "Dense mango orchard belt in Krishna-NTR border produces Banganapalle and Totapuri varieties. Lack of local packhouse causes fruit fly vulnerability and loss of export premiums during April-June harvest window.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 5. Chittoor - Critical
  {
    id: "pot-ctr-001",
    clusterName: "Bangarupalem - Baireddipalle Mango & Pulp Buffer Facility",
    district: "Chittoor",
    mandal: "Bangarupalem",
    suggestedCoordinates: { lat: 13.1950, lng: 78.9650 },
    priorityScore: 92,
    urgencyLevel: "Critical Priority",
    localProduceAtRiskMTPerYear: 138000,
    primaryTargetCommodities: ["Mango", "Tomato", "Papaya"],
    distanceToNearestExistingColdStorageKm: 27.5,
    recommendedCapacityMT: 8000,
    recommendedChamberType: "Dual Pre-cooling and Deep Freeze Aseptic Pulp Buffer (-18°C)",
    estimatedCapexCroresINR: 12.0,
    paybackPeriodYears: 4.0,
    connectivity: "NH-69 Bangalore - Chennai Industrial Expressway corridor",
    rationale: "Over 80 pulp manufacturing units in Chittoor district depend on smooth mango intake. Processing bottlenecks during peak arrivals cause open-air decay of up to 40,000 MT of high-grade Totapuri fruit.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 6. Guntur - Critical
  {
    id: "pot-gnt-001",
    clusterName: "Prathipadu - Pedanandipadu Chilli & Turmeric Feeder Depot",
    district: "Guntur",
    mandal: "Prathipadu",
    suggestedCoordinates: { lat: 16.1420, lng: 80.3210 },
    priorityScore: 91,
    urgencyLevel: "Critical Priority",
    localProduceAtRiskMTPerYear: 128000,
    primaryTargetCommodities: ["Fresh Chilli", "Turmeric"],
    distanceToNearestExistingColdStorageKm: 26.0,
    recommendedCapacityMT: 8000,
    recommendedChamberType: "Automated Temperature & Low-Humidity Spice Preservation CA Chamber",
    estimatedCapexCroresINR: 11.5,
    paybackPeriodYears: 3.9,
    connectivity: "NH-16 linking Guntur and Chennai",
    rationale: "Southern Guntur black cotton soil produces high-oleoresin Teja chilli. Central Guntur cold stores reach 98% occupancy by March, leaving small and marginal farmers with no storage options.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 7. Nandyal - Critical
  {
    id: "pot-ndl-001",
    clusterName: "Banaganapalle - Owk Mango & Turmeric Preservation Terminal",
    district: "Nandyal",
    mandal: "Banaganapalle",
    suggestedCoordinates: { lat: 15.3210, lng: 78.2190 },
    priorityScore: 90,
    urgencyLevel: "Critical Priority",
    localProduceAtRiskMTPerYear: 118000,
    primaryTargetCommodities: ["Mango", "Turmeric", "Banana"],
    distanceToNearestExistingColdStorageKm: 38.0,
    recommendedCapacityMT: 7000,
    recommendedChamberType: "Combined CA Fruit Cell (10-12°C) and Spice Preservation Chamber (4-8°C)",
    estimatedCapexCroresINR: 10.5,
    paybackPeriodYears: 4.2,
    connectivity: "SH-30 connecting Banaganapalle with Tadipatri and Nandyal",
    rationale: "The geographical origin of the GI-tagged 'Banaganapalle Mango' lacks cold storage at the mandal level. Farmers must transport sensitive produce 40 km to Nandyal town, suffering quality degradation.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 8. Palnadu - High
  {
    id: "pot-pln-001",
    clusterName: "Vinukonda - Macherla High-Grade Fresh Chilli & Vegetable Facility",
    district: "Palnadu",
    mandal: "Vinukonda",
    suggestedCoordinates: { lat: 16.0540, lng: 79.7420 },
    priorityScore: 89,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 115000,
    primaryTargetCommodities: ["Fresh Chilli", "Tomato", "Lime"],
    distanceToNearestExistingColdStorageKm: 34.0,
    recommendedCapacityMT: 6500,
    recommendedChamberType: "Dual Temperature Cold Chambers (4-8°C and 8-12°C)",
    estimatedCapexCroresINR: 9.6,
    paybackPeriodYears: 4.4,
    connectivity: "NH-544D linking Guntur, Nandyal and Anantapur",
    rationale: "Western Palnadu farmers travel 60+ km to Guntur city to find cold storage for fresh chillies and vegetables, causing high transport costs and deterioration during transit. A local facility will serve 45+ villages directly.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 9. Sri Sathya Sai - High
  {
    id: "pot-sss-001",
    clusterName: "Kadiri - Gandlapenta Sweet Orange & Pomegranate Center",
    district: "Sri Sathya Sai",
    mandal: "Kadiri",
    suggestedCoordinates: { lat: 14.1150, lng: 78.1650 },
    priorityScore: 88,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 104000,
    primaryTargetCommodities: ["Sweet Orange", "Pomegranate", "Mango"],
    distanceToNearestExistingColdStorageKm: 46.0,
    recommendedCapacityMT: 6000,
    recommendedChamberType: "Controlled Humidity Semi-Arid Horticulture Chilling Chambers",
    estimatedCapexCroresINR: 9.2,
    paybackPeriodYears: 4.3,
    connectivity: "NH-42 connecting Madanapalle, Kadiri and Anantapur",
    rationale: "Drought-prone Kadiri basin has expanded drip-irrigated citrus and pomegranate cultivation. High daytime heat (38-42°C) causes rapid rind desiccations and fungal fruit rot without immediate post-harvest chilling.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 10. Alluri Sitharama Raju - High
  {
    id: "pot-asr-001",
    clusterName: "Chintapalle - G.K.Veedhi Tribal Agency Spices & Ginger Depot",
    district: "Alluri Sitharama Raju",
    mandal: "Chintapalle",
    suggestedCoordinates: { lat: 17.8720, lng: 82.3510 },
    priorityScore: 88,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 78000,
    primaryTargetCommodities: ["Ginger", "Turmeric", "Coffee", "Black Pepper"],
    distanceToNearestExistingColdStorageKm: 52.0,
    recommendedCapacityMT: 4500,
    recommendedChamberType: "Solar-Hybrid Micro Cold Chain with Low-Moisture Storage",
    estimatedCapexCroresINR: 7.2,
    paybackPeriodYears: 4.5,
    connectivity: "Ghat Road SH-38 linking Chintapalle, Narsipatnam and Anakapalli",
    rationale: "High-altitude tribal farmers harvest high-curcumin organic turmeric and ginger. Lack of localized cold storage forces reliance on exploitative middlemen and causes weight losses of over 22% during open transport.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 11. Ananthapuramu - High
  {
    id: "pot-atp-001",
    clusterName: "Uravakonda - Beluguppa Sweet Orange (Mosambi) Cold Hub",
    district: "Ananthapuramu",
    mandal: "Uravakonda",
    suggestedCoordinates: { lat: 14.9450, lng: 77.2580 },
    priorityScore: 87,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 98000,
    primaryTargetCommodities: ["Sweet Orange", "Pomegranate", "Papaya"],
    distanceToNearestExistingColdStorageKm: 48.0,
    recommendedCapacityMT: 6000,
    recommendedChamberType: "Multi-Chamber with Controlled Humidity & Fungicide Post-Harvest Wash",
    estimatedCapexCroresINR: 9.0,
    paybackPeriodYears: 4.2,
    connectivity: "NH-67 linking Bellary and Anantapur",
    rationale: "Sweet orange growers suffer heavy skin shriveling and decay in semi-arid Rayalaseema heat without immediate pre-cooling and cold storage within 2 hours of harvest.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 12. East Godavari - High
  {
    id: "pot-egd-001",
    clusterName: "Korukonda - Gokavaram Godavari Basin Banana & Cocoa Cold Depot",
    district: "East Godavari",
    mandal: "Korukonda",
    suggestedCoordinates: { lat: 17.1820, lng: 81.8250 },
    priorityScore: 87,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 108000,
    primaryTargetCommodities: ["Banana", "Cocoa", "Cashew", "Mango"],
    distanceToNearestExistingColdStorageKm: 31.0,
    recommendedCapacityMT: 6500,
    recommendedChamberType: "Refrigerated Transit Dock with Controlled Humidity Cocoa Pod Holding",
    estimatedCapexCroresINR: 9.8,
    paybackPeriodYears: 4.1,
    connectivity: "SH-41 connecting Rajahmundry, Gokavaram and Rampachodavaram",
    rationale: "Fertile alluvial tracts along the Godavari river cultivate Cavendish bananas and cocoa as intercrop. High tropical humidity triggers rapid anthracnose and stem-end rot unless chilled to 13°C within 4 hours.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 13. Bapatla - High
  {
    id: "pot-bpt-001",
    clusterName: "Addanki - Santhanuthalapadu Chilli & Vegetable Cold Terminal",
    district: "Bapatla",
    mandal: "Addanki",
    suggestedCoordinates: { lat: 15.8110, lng: 79.9820 },
    priorityScore: 86,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 92000,
    primaryTargetCommodities: ["Fresh Chilli", "Banana", "Vegetables"],
    distanceToNearestExistingColdStorageKm: 35.0,
    recommendedCapacityMT: 5500,
    recommendedChamberType: "Dual Multi-Commodity Chamber with Forced-Air Cooling",
    estimatedCapexCroresINR: 8.2,
    paybackPeriodYears: 4.4,
    connectivity: "State Highway linking Addanki with Ongole and Chilakaluripet",
    rationale: "Located at the tri-border of Bapatla, Prakasam and Palnadu. Addanki produces high volumes of green chillies and vegetables for Vijayawada and Chennai wholesale markets.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 14. Parvathipuram Manyam - High
  {
    id: "pot-pvm-001",
    clusterName: "Palakonda - Veeraghattam Tribal Agro & Cashew Processing Depot",
    district: "Parvathipuram Manyam",
    mandal: "Palakonda",
    suggestedCoordinates: { lat: 18.6010, lng: 83.7550 },
    priorityScore: 86,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 74000,
    primaryTargetCommodities: ["Cashew", "Mango", "Turmeric"],
    distanceToNearestExistingColdStorageKm: 41.0,
    recommendedCapacityMT: 5000,
    recommendedChamberType: "De-humidified Raw Cashew Nut Storage and Pre-cooling Unit",
    estimatedCapexCroresINR: 7.5,
    paybackPeriodYears: 4.5,
    connectivity: "SH-2 linking Parvathipuram, Palakonda and Srikakulam",
    rationale: "Northern tribal belt produces pesticide-free organic cashew and mangoes. Farmers lose up to 30% of nut quality to seasonal monsoon mould during prolonged storage without controlled humidity.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 15. YSR Kadapa - High
  {
    id: "pot-kdp-001",
    clusterName: "Jammalamadugu - Mylavaram Banana & Papaya Packhouse",
    district: "YSR Kadapa",
    mandal: "Jammalamadugu",
    suggestedCoordinates: { lat: 14.8510, lng: 78.3810 },
    priorityScore: 85,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 88000,
    primaryTargetCommodities: ["Banana", "Papaya", "Turmeric"],
    distanceToNearestExistingColdStorageKm: 31.0,
    recommendedCapacityMT: 5000,
    recommendedChamberType: "Refrigerated Transit Pre-cooling & Ripening Facility (13-15°C)",
    estimatedCapexCroresINR: 7.8,
    paybackPeriodYears: 4.0,
    connectivity: "SH-28 connecting Proddatur, Tadipatri and Bellary",
    rationale: "Penna river basin produces export-grade Grand Naine bananas, but lack of pre-cooling facilities forces farmers to sell at field gates at sub-optimal prices.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 16. Prakasam - High
  {
    id: "pot-pkm-001",
    clusterName: "Giddalur - Cumbum Semi-Arid Chilli & Tomato Center",
    district: "Prakasam",
    mandal: "Giddalur",
    suggestedCoordinates: { lat: 15.3850, lng: 78.9320 },
    priorityScore: 85,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 82000,
    primaryTargetCommodities: ["Fresh Chilli", "Tomato", "Sweet Orange"],
    distanceToNearestExistingColdStorageKm: 44.0,
    recommendedCapacityMT: 5000,
    recommendedChamberType: "Multi-Chamber Produce Chilling Unit (4°C to 10°C)",
    estimatedCapexCroresINR: 7.6,
    paybackPeriodYears: 4.3,
    connectivity: "State Highway connecting Giddalur with Nandyal and Ongole",
    rationale: "Western Nallamala foothill tract suffers severe post-harvest tomato gluts. Establishing a localized facility reduces transport distance from 110km to less than 15km for 30+ villages.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 17. Srikakulam - High
  {
    id: "pot-skl-001",
    clusterName: "Tekkali - Sompeta Coastal Cashew & Fruit Cold Station",
    district: "Srikakulam",
    mandal: "Tekkali",
    suggestedCoordinates: { lat: 18.6180, lng: 84.2380 },
    priorityScore: 85,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 86000,
    primaryTargetCommodities: ["Cashew", "Mango", "Banana"],
    distanceToNearestExistingColdStorageKm: 33.0,
    recommendedCapacityMT: 5500,
    recommendedChamberType: "De-humidified Low Temperature Cashew & Fruit Storage Cell",
    estimatedCapexCroresINR: 8.4,
    paybackPeriodYears: 4.4,
    connectivity: "NH-16 Chennai - Kolkata Golden Quadrilateral",
    rationale: "Northern coastal belt of Srikakulam handles substantial cashew harvests and Banganapalle mangoes. Extreme coastal humidity damages raw cashew shells and causes premature mango softening without cold chain.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 18. Krishna - High
  {
    id: "pot-kri-001",
    clusterName: "Avanigadda - Nagayalanka Coastal Banana & Guava Depot",
    district: "Krishna",
    mandal: "Avanigadda",
    suggestedCoordinates: { lat: 16.0210, lng: 80.9180 },
    priorityScore: 84,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 78000,
    primaryTargetCommodities: ["Banana", "Guava", "Vegetables"],
    distanceToNearestExistingColdStorageKm: 39.0,
    recommendedCapacityMT: 5000,
    recommendedChamberType: "Banana Controlled Ripening & Chilling Chambers (12-14°C)",
    estimatedCapexCroresINR: 7.6,
    paybackPeriodYears: 4.2,
    connectivity: "NH-216 Coastal Highway connecting Machilipatnam, Avanigadda and Ongole",
    rationale: "Krishna river island farmers produce heavy yields of Karpura and Grand Naine bananas. Lack of cold chain on the delta bank forces farmers to sell at distress rates during cyclone threats and heavy rain gluts.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 19. Dr. B.R. Ambedkar Konaseema - High
  {
    id: "pot-kns-001",
    clusterName: "Razole - Sakhinetipalli River Island Banana & Produce Terminal",
    district: "Dr. B.R. Ambedkar Konaseema",
    mandal: "Razole",
    suggestedCoordinates: { lat: 16.4820, lng: 81.8350 },
    priorityScore: 84,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 82000,
    primaryTargetCommodities: ["Banana", "Papaya", "Cashew"],
    distanceToNearestExistingColdStorageKm: 36.0,
    recommendedCapacityMT: 5000,
    recommendedChamberType: "Ethylene Scrubbed Pre-cooling & Ripening Facility",
    estimatedCapexCroresINR: 7.7,
    paybackPeriodYears: 4.3,
    connectivity: "NH-216 and inland waterway barge connectivity",
    rationale: "Konaseema island belt is encircled by Godavari distributaries. Ferry bottlenecks delay transit to mainland cold stores, triggering transit decay of up to 25% for ripe banana bunches.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 20. Tirupati - High
  {
    id: "pot-tpt-001",
    clusterName: "Venkatagiri - Dakkili Citrus, Lime & Horticultural Hub",
    district: "Tirupati",
    mandal: "Venkatagiri",
    suggestedCoordinates: { lat: 13.9650, lng: 79.5820 },
    priorityScore: 83,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 76000,
    primaryTargetCommodities: ["Lime", "Tomato", "Mango"],
    distanceToNearestExistingColdStorageKm: 37.0,
    recommendedCapacityMT: 4500,
    recommendedChamberType: "Controlled Temperature & Waxing Post-Harvest Unit (7-10°C)",
    estimatedCapexCroresINR: 6.9,
    paybackPeriodYears: 4.4,
    connectivity: "State Highway 61 linking Venkatagiri, Gudur and Tirupati",
    rationale: "Acid lime growers in Venkatagiri valley face high spoilage in dry Rayalaseema heat. Cold holding facilities will allow orderly marketing into Chennai and Tirupati pilgrim markets.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 21. Vizianagaram - High
  {
    id: "pot-vzm-001",
    clusterName: "Gajapathinagaram - Badangi Mango & Cashew Cold Facility",
    district: "Vizianagaram",
    mandal: "Gajapathinagaram",
    suggestedCoordinates: { lat: 18.2820, lng: 83.3350 },
    priorityScore: 83,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 84000,
    primaryTargetCommodities: ["Mango", "Cashew", "Tomato"],
    distanceToNearestExistingColdStorageKm: 29.0,
    recommendedCapacityMT: 5000,
    recommendedChamberType: "Pre-cooling & Palletized Multi-Commodity Cold Store",
    estimatedCapexCroresINR: 7.5,
    paybackPeriodYears: 4.4,
    connectivity: "NH-26 linking Vizianagaram, Bobbili and Raipur",
    rationale: "Major Suvarnarekha and Banganapalle mango production tract. Cold staging prevents skin blotching and extends shelf life by 3 weeks, enabling sales to northern state markets via rail corridors.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 22. Kakinada - Medium
  {
    id: "pot-kkd-001",
    clusterName: "Pithapuram - Gollaprolu Cashew & Tropical Fruit Cold Station",
    district: "Kakinada",
    mandal: "Pithapuram",
    suggestedCoordinates: { lat: 17.1120, lng: 82.2590 },
    priorityScore: 82,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 72000,
    primaryTargetCommodities: ["Cashew", "Mango", "Banana"],
    distanceToNearestExistingColdStorageKm: 27.0,
    recommendedCapacityMT: 4500,
    recommendedChamberType: "De-humidified Raw Nut Cell and Fruit Cold Chamber",
    estimatedCapexCroresINR: 6.8,
    paybackPeriodYears: 4.5,
    connectivity: "NH-16 and Kakinada Port feeder road",
    rationale: "Pithapuram cashew and mango farms experience high post-harvest losses during early monsoons. Direct cold staging supports value addition for local women self-help group processing clusters.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 23. Visakhapatnam - Medium
  {
    id: "pot-vsp-001",
    clusterName: "Bheemunipatnam - Tagarapuvalasa Urban Periphery Vegetable Cold Hub",
    district: "Visakhapatnam",
    mandal: "Bheemunipatnam",
    suggestedCoordinates: { lat: 17.8920, lng: 83.4350 },
    priorityScore: 82,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 68000,
    primaryTargetCommodities: ["Vegetables", "Tomato", "Cashew"],
    distanceToNearestExistingColdStorageKm: 28.0,
    recommendedCapacityMT: 4500,
    recommendedChamberType: "Urban Consumer Supply Pre-cooling & Multi-Chamber (2-6°C)",
    estimatedCapexCroresINR: 7.0,
    paybackPeriodYears: 4.2,
    connectivity: "Visakhapatnam - Bheemunipatnam Coastal Beach Corridor & NH-16",
    rationale: "Serves as the vital perishable supply buffer for the Visakhapatnam metropolitan area (pop. 2.4 million). Cushions mid-day heat wilting for local peri-urban farmers.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 24. Anakapalli - Medium
  {
    id: "pot-akp-001",
    clusterName: "Chodavaram - K.Kotapadu Organic Produce & Vegetable Center",
    district: "Anakapalli",
    mandal: "Chodavaram",
    suggestedCoordinates: { lat: 17.8320, lng: 82.9450 },
    priorityScore: 81,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 62000,
    primaryTargetCommodities: ["Tomato", "Vegetables", "Cashew", "Mango"],
    distanceToNearestExistingColdStorageKm: 29.0,
    recommendedCapacityMT: 4000,
    recommendedChamberType: "Solar-Assisted Micro Cold Storage Hub with Pre-cooling",
    estimatedCapexCroresINR: 6.2,
    paybackPeriodYears: 4.6,
    connectivity: "State Highway 9 connecting Anakapalli & Paderu tribal agency tracts",
    rationale: "Direct supply line for Visakhapatnam urban consumption zone. Prevents mid-day wilting and spoilage for smallholder vegetable and fruit growers.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 25. West Godavari - Medium
  {
    id: "pot-wgd-001",
    clusterName: "Narasapuram - Palakollu Coastal Guava & Horticulture Packhouse",
    district: "West Godavari",
    mandal: "Narasapuram",
    suggestedCoordinates: { lat: 16.4420, lng: 81.6980 },
    priorityScore: 80,
    urgencyLevel: "High Priority",
    localProduceAtRiskMTPerYear: 66000,
    primaryTargetCommodities: ["Guava", "Banana", "Vegetables"],
    distanceToNearestExistingColdStorageKm: 32.0,
    recommendedCapacityMT: 4000,
    recommendedChamberType: "Pre-cooling and Controlled Temperature Storage (8-12°C)",
    estimatedCapexCroresINR: 6.3,
    paybackPeriodYears: 4.4,
    connectivity: "NH-216 Coastal Highway",
    rationale: "Vast guava orchards in Palakollu and Mogalthur produce high-yield Allahabad Safeda and Taiwan varieties. Guavas soften rapidly within 36 hours of plucking in coastal heat without pre-cooling.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  },

  // 26. Eluru - Medium
  {
    id: "pot-elr-001",
    clusterName: "Chintalapudi - Kamavarapukota Inland Agro Buffer Station",
    district: "Eluru",
    mandal: "Jangareddigudem",
    suggestedCoordinates: { lat: 17.0620, lng: 81.1450 },
    priorityScore: 79,
    urgencyLevel: "Medium Priority",
    localProduceAtRiskMTPerYear: 58000,
    primaryTargetCommodities: ["Cocoa", "Banana", "Mango"],
    distanceToNearestExistingColdStorageKm: 36.0,
    recommendedCapacityMT: 4000,
    recommendedChamberType: "Multi-Commodity Pre-cooling & Humidity Regulated Cell",
    estimatedCapexCroresINR: 6.1,
    paybackPeriodYears: 4.5,
    connectivity: "SH-42 connecting Jangareddigudem and Chintalapudi to Vijayawada",
    rationale: "Inland red-loam belt produces high volumes of cocoa pods and mangoes. Farmers face high freight costs to Eluru city, leading to on-farm degradation during peak summer heat.",
    source: "GIS Catchment & Cluster Algorithm",
    sourceType: "Platform Calculated",
    sourceLastUpdated: "2026-09-27T00:00:00.000Z",
    lastVerified: "2026-09-27T00:00:00.000Z"
  }
];
